/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef DM_IPC_INTERFACE_CODE_H
#define DM_IPC_INTERFACE_CODE_H

#include <stdint.h>

typedef enum DmIpcCmdInterfaceCode {
    DM_REGISTER_DEVICE_MANAGER_LISTENER = 0,
    DM_UNREGISTER_DEVICE_MANAGER_LISTENER,
    DM_GET_TRUST_DEVICE_LIST,
    DM_GET_LOCAL_DEVICE_INFO,
    DM_GET_UDID_BY_NETWORK,
    DM_GET_UUID_BY_NETWORK,
    DM_GET_NETWORKTYPE_BY_NETWORK,
    DM_PUBLISH_DEVICE_DISCOVER,
    DM_UNPUBLISH_DEVICE_DISCOVER,
    DM_SERVER_DEVICE_STATE_NOTIFY,
    DM_SERVER_DEVICE_FOUND,
    DM_SERVER_DEVICE_DISCOVERY,
    DM_SERVER_DISCOVER_FINISH,
    DM_SERVER_PUBLISH_FINISH,
    DM_SERVER_GET_DMFA_INFO,
    DM_SERVER_DEVICE_FA_NOTIFY,
    DM_SERVER_CREDENTIAL_RESULT,
    DM_REGISTER_DEV_STATE_CALLBACK,
    DM_UNREGISTER_DEV_STATE_CALLBACK,
    DM_REQUEST_CREDENTIAL,
    DM_IMPORT_CREDENTIAL,
    DM_DELETE_CREDENTIAL,
    DM_REGISTER_CREDENTIAL_CALLBACK,
    DM_UNREGISTER_CREDENTIAL_CALLBACK,
    DM_NOTIFY_EVENT,
    DM_GET_DEVICE_INFO,
    DM_REGISTER_UI_STATE_CALLBACK,
    DM_UNREGISTER_UI_STATE_CALLBACK,
    DM_REGISTER_DISCOVERY_CALLBACK,
    DM_UNREGISTER_DISCOVERY_CALLBACK,
    DM_START_DISCOVERING,
    DM_STOP_DISCOVERING,
    DM_START_ADVERTISING,
    DM_STOP_ADVERTISING,
    DM_DP_ACL_ADD,
    DM_GET_SECURITY_LEVEL,
    DM_IS_SAME_ACCOUNT,
    DM_CHECK_API_PERMISSION,
    DM_CHECK_ACCESS_CONTROL,
    DM_CHECK_SAME_ACCOUNT,
    DM_SHIFT_LNN_GEAR,
    DM_SET_DN_POLICY,
    DM_REMOTE_DEVICE_TRUST_CHANGE,
    DM_SERVER_DEVICE_SCREEN_STATE_NOTIFY,
    DM_GET_DEVICE_SCREEN_STATUS,
    DM_GET_NETWORKID_BY_UDID,
    DM_SERVICE_CREDENTIAL_AUTH_STATUS_NOTIFY,
    DM_SYNC_CALLBACK,
    DM_GET_ANONY_LOCAL_UDID,
    DM_GET_DEVICE_PROFILE_INFO_LIST,
    DM_GET_DEVICE_PROFILE_INFO_LIST_RESULT,
    DM_GET_DEVICE_ICON_INFO,
    DM_GET_DEVICE_ICON_INFO_RESULT,
    DM_PUT_DEVICE_PROFILE_INFO_LIST,
    DM_GET_LOCAL_DISPLAY_DEVICE_NAME,
    DM_SET_REMOTE_DEVICE_NAME,
    DM_SET_REMOTE_DEVICE_NAME_RESULT,
    DM_SET_LOCAL_DEVICE_NAME,
    DM_SET_LOCAL_DEVICE_NAME_RESULT,
    DM_GET_ALL_TRUST_DEVICE_LIST,
    DM_GET_DEVICE_NETWORK_ID_LIST,
    DM_RESTORE_LOCAL_DEVICE_NAME,
    DM_REG_LOCALSERVICE_INFO,
    DM_UNREG_LOCALSERVICE_INFO,
    DM_UPDATE_LOCALSERVICE_INFO,
    DM_GET_SERVICEINFO_BYBUNDLENAME_PINEXCHANGETYPE,
    DM_GET_LOCAL_DEVICE_NAME,
    DM_GET_LOCAL_DEVICE_NAME_OLD,
    DM_CHECK_SRC_ACCESS_CONTROL,
    DM_CHECK_SINK_ACCESS_CONTROL,
    DM_CHECK_SRC_SAME_ACCOUNT,
    DM_CHECK_SINK_SAME_ACCOUNT,
    DM_START_SERVICE_DISCOVERING,
    DM_STOP_SERVICE_DISCOVERING,
    DM_NOTIFY_SERVICE_FOUND,
    DM_NOTIFY_SERVICE_DISCOVERY_RESULT,
    DM_REGISTER_SERVICE_INFO,
    DM_UNREGISTER_SERVICE_INFO,
    DM_START_PUBLISH_SERVICE,
    DM_STOP_PUBLISH_SERVICE,
    DM_SERVICE_PUBLISH_RESULT,
    DM_GET_UDIDS_BY_DEVICEIDS,
    DM_GET_IDENTIFICATION_BY_DEVICEIDS,
    DM_LEAVE_LNN,
    DM_LEAVE_LNN_RESULT,
    DM_SYNC_SERVICE_CALLBACK,
    DM_SERVER_SERVICE_STATE_NOTIFY,
    DM_SYNC_SERVICE_INFO,
    DM_SYNC_SERVICE_INFO_RESULT,
    DM_GET_LOCAL_SERVICEINFO_BY_SERVICEID,
    DM_GET_TRUST_SERVICE_INFO,
    DM_GET_REGISTER_SERVICE_INFO,
    DM_GET_PEER_SERVICEINFO_BY_SERVICEID,
    DM_UPDATE_SERVICE_INFO,
    DM_TEST_TRIGGER_ACL_WRITE,
    DM_TEST_TRIGGER_CRED_DELETE,
    DM_IPC_MSG_BUTT
} DmIpcCmdInterfaceCode;

#define IPC_MSG_BUTT DM_IPC_MSG_BUTT

#endif
