# Copyright (c) 2022-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//foundation/distributedhardware/device_manager/device_manager.gni")

config("devicemanagersdk_config") {
    include_dirs = [
      "include",
      "include/ipc",
      "include/ipc",
      "include/notify",
      "${lite_common_path}/include",
      "${lite_common_path}/include/ipc",
      "${lite_common_path}/include/ipc/model",
      "${lite_common_path}/include/ipc",
      "${lite_common_path}/include/dfx",
      "${lite_common_path}/include/dfx",
      "${lite_utils_path}/include",
      "${lite_json_path}/include",
      "//foundation/communication/dsoftbus/interfaces/kits/bus_center",
      "//foundation/communication/dsoftbus/interfaces/kits/common",
    ]
  }

  ohos_shared_library("devicemanagersdk") {
    if (defined(ohos_lite)) {
      output_extension = "so"
    }
    branch_protector_ret = "pac_ret"

    if (!defined(ohos_lite)) {
      sanitize = {
        boundary_sanitize = true
        integer_overflow = true
        ubsan = true
      }
    }

    cflags = [
      "-Werror",
      "-fPIC",
      "-fstack-protector-strong",
    ]

    cflags_c = [
      "-std=c99",
    ]

    cflags_cc = [
      "-std=c++17",
      "-fno-exceptions",
      "-fno-rtti",
    ]

    ldflags = [
      "-Wl,-z,relro",
      "-Wl,-z,now",
    ]

    if (!device_manager_capability) {
      sources = []
    } else if (defined(ohos_lite)) {
      sources = [
        "src/device_manager.c",
        "src/device_manager_impl.c",
        "src/notify/device_manager_notify.c",
        "src/ipc/ipc_client_manager.c",
        "src/ipc/ipc_client_server_proxy.c",
        "src/ipc/ipc_client_stub.c",
        "src/ipc/ipc_cmd_parser.c",
        "${lite_common_path}/src/dm_anonymous.c",
        "${lite_common_path}/src/dm_container.c",
        "${lite_common_path}/src/dm_thread.c",
        "${lite_common_path}/src/dm_device_info_c.c",
        "${lite_common_path}/src/dm_device_profile_info_c.c",
        "${lite_common_path}/src/ipc/ipc_cmd_register.c",
        "${lite_common_path}/src/ipc/ipc_model_codec_shell_lite.c",
        "${lite_common_path}/src/ipc/model/ipc_check_access_control.c",
        "${lite_common_path}/src/ipc/model/ipc_req.c",
        "${lite_common_path}/src/ipc/model/ipc_rsp.c",
      ]
    } else {
      sources = [
        "${lite_common_path}/src/dm_anonymous.c",
        "${lite_common_path}/src/dm_container.c",
        "${lite_common_path}/src/dm_thread.c",
        "${lite_common_path}/src/dm_device_info_c.c",
        "${lite_common_path}/src/dm_device_profile_info_c.c",
        "${lite_common_path}/src/ipc/ipc_cmd_register.c",
        "${lite_common_path}/src/ipc/ipc_model_codec_shell_lite.c",
        "${lite_common_path}/src/ipc/model/ipc_check_access_control.c",
        "${lite_common_path}/src/ipc/model/ipc_req.c",
        "${lite_common_path}/src/ipc/model/ipc_rsp.c",
        "${lite_utils_path}/src/dm_random.c",
        "src/device_manager.c",
        "src/device_manager_impl.c",
        "src/ipc/ipc_client_manager.c",
        "src/ipc/ipc_client_server_proxy.c",
        "src/ipc/ipc_client_stub.c",
        "src/ipc/ipc_cmd_parser.c",
        "src/notify/device_manager_notify.c",
      ]
    }

    public_configs = [ ":devicemanagersdk_config" ]

    innerapi_tags = [ "platformsdk" ]

    defines = [
      "HI_LOG_ENABLE",
      "DH_LOG_TAG=\"dmkit\"",
      "LOG_DOMAIN=0xD004111",
    ]

    deps = [ "${lite_json_path}:devicemanagerjson" ]

    if (defined(ohos_lite)) {
      deps += [ "//foundation/distributedhardware/device_manager/lite:dm_lite_external_deps" ]
    } else if (device_manager_capability) {
      external_deps = [
        "access_token:libaccesstoken_sdk",
        "access_token:libtokenid_sdk",
        "cJSON:cjson",
        "c_utils:utils",
        "ffrt:libffrt",
        "hilog:libhilog",
        "hisysevent:libhisysevent",
        "hitrace:hitrace_meter",
        "init:libbegetutil",
        "ipc:ipc_core",
        "ipc:ipc_napi",
        "ipc:ipc_single",
        "ipc:libdbinder",
        "openssl:libcrypto_shared",
        "samgr:samgr_proxy",
      ]
    }

    subsystem_name = "distributedhardware"

    part_name = "device_manager"
  }
