/*
 * Copyright (c) 2022-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Refactored artifact generated by the secure-code-refactor skill.
 * Source: services/service/src/discovery/discovery_manager.cpp (unchanged).
 * Principle tags at changed sites: [P2] identity source, [P3] device/input validation,
 * [P12] resource cleanup, [P13/P15] fail-closed ACL dependency, [P18] user isolation,
 * [P21] custom field control, [FIX] integrity fix.
 */

#include "discovery_manager_Refactor.h"

#include <cstdint>
#include <cstring>
#include <vector>

#include <dlfcn.h>
#include "softbus_common.h"

#include "dm_anonymous.h"
#include "dm_constants.h"
#include "dm_random.h"
#include "parameter.h"
#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
#include "multiple_user_connector.h"
#endif

namespace OHOS {
namespace DistributedHardware {
const int32_t DISCOVERY_TIMEOUT = 120;
const uint16_t DM_INVALID_FLAG_ID = 0;
constexpr const char* LNN_DISC_CAPABILITY = "capability";
const std::string TYPE_MINE = "findDeviceMode";
const int32_t DECIMALISM = 10;
constexpr int32_t PARAM_VALID = 1;
constexpr int32_t PARAM_ABSENT = 0;
constexpr int32_t PARAM_INVALID = -1;
// [P2] pkgName composes multi-user keys with '#'; bound its length.
constexpr size_t MAX_PKG_NAME_LEN = 256;
// [P21] custom data broadcast in discovery is length-bounded.
constexpr size_t MAX_CUSTOM_DATA_LEN = 512;
// [P21] filter options/search json from the caller is length-bounded.
constexpr size_t MAX_FILTER_DATA_LEN = 4096;

#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
static std::mutex comDependencyLoadLock;
constexpr const char* LIB_DM_COMDENPENDENCY_NAME = "libdevicemanagerdependency.z.so";
bool DiscoveryManager::isSoLoaded_ = false;
IDeviceProfileConnector* DiscoveryManager::dpConnector_ = nullptr;
void* DiscoveryManager::dpConnectorHandle_ = nullptr;
#endif

DiscoveryManager::DiscoveryManager(std::shared_ptr<SoftbusListener> softbusListener,
    std::shared_ptr<IDeviceManagerServiceListener> listener) : softbusListener_(softbusListener), listener_(listener)
{
    LOGI("constructor.");
}

DiscoveryManager::~DiscoveryManager()
{
#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
    CloseCommonDependencyObj();
#endif
    LOGI("destructor.");
}

void DiscoveryManager::SecureClearString(std::string &str)
{
    // [P12] zero the buffer before release so sensitive plaintext (e.g. local udid) does not
    // remain in freed heap memory.
    if (str.empty()) {
        return;
    }
    volatile char *addr = &str[0];
    for (size_t i = 0; i < str.size(); i++) {
        addr[i] = 0;
    }
    str.clear();
}

void DiscoveryManager::SecureClearBuffer(char *buf, size_t len)
{
    // [P12] zero the stack buffer that once held the local udid.
    if (buf == nullptr || len == 0) {
        return;
    }
    volatile char *addr = buf;
    for (size_t i = 0; i < len; i++) {
        addr[i] = 0;
    }
}

bool DiscoveryManager::IsValidPkgName(const std::string &pkgName)
{
    // [P2] pkgName composes multi-user keys with '#'; reject empty, over-long, or
    // separator-bearing names to prevent identity composition corruption and cross-caller
    // key collisions.
    if (pkgName.empty() || pkgName.size() > MAX_PKG_NAME_LEN ||
        pkgName.find('#') != std::string::npos) {
        LOGE("pkgName is invalid.");
        return false;
    }
    return true;
}

bool DiscoveryManager::IsValidCapability(const std::string &capability)
{
    // [P21] capability comes from the caller and is broadcast in discovery; it must belong to
    // the known capability set.
    for (uint32_t i = 0; i < sizeof(g_capabilityMap) / sizeof(g_capabilityMap[0]); i++) {
        if (strcmp(capability.c_str(), g_capabilityMap[i].capability) == 0) {
            return true;
        }
    }
    LOGE("capability is not in known set.");
    return false;
}

int32_t DiscoveryManager::GetValidatedInt(const std::map<std::string, std::string> &param, const char *key,
    int32_t minVal, int32_t maxVal, int32_t &out)
{
    auto it = param.find(key);
    if (it == param.end()) {
        return PARAM_ABSENT;
    }
    // [P3] numeric string with explicit range check; invalid values never reach the enum/uint16 cast.
    if (!IsNumberString(it->second)) {
        LOGE("param %{public}s is not numeric.", key);
        return PARAM_INVALID;
    }
    int32_t value = StringToInt(it->second, DECIMALISM);
    if (value < minVal || value > maxVal) {
        LOGE("param %{public}s out of range.", key);
        return PARAM_INVALID;
    }
    out = value;
    return PARAM_VALID;
}

int32_t DiscoveryManager::EnableDiscoveryListener(const std::string &pkgName,
    const std::map<std::string, std::string> &discoverParam, const std::map<std::string, std::string> &filterOptions)
{
    if (!IsValidPkgName(pkgName)) {
        LOGE("Invalid parameter, pkgName is invalid.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    CHECK_NULL_RETURN(softbusListener_, ERR_DM_POINT_NULL);
    LOGI("begin for pkgName = %{public}s.", pkgName.c_str());
    std::string pkgNameTemp = AddMultiUserIdentify(pkgName);
    if (pkgNameTemp.empty()) {
        return ERR_DM_FAILED;
    }
    DmSubscribeInfo dmSubInfo;
    int32_t ret = InitPassiveSubInfo(pkgNameTemp, discoverParam, dmSubInfo);
    if (ret != DM_OK) {
        return ret;
    }
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        CHECK_SIZE_RETURN(capabilityMap_, ERR_DM_ENABLE_DISCOVERY_LISTENER_FAILED);
        capabilityMap_[pkgNameTemp] = std::string(dmSubInfo.capability);
    }
    ret = softbusListener_->RefreshSoftbusLNN(DM_PKG_NAME, dmSubInfo, LNN_DISC_CAPABILITY);
    if (ret != DM_OK) {
        LOGE("softbus refresh lnn ret: %{public}d.", ret);
        return ret;
    }
    softbusListener_->RegisterSoftbusLnnOpsCbk(pkgNameTemp, shared_from_this());
    return DM_OK;
}

int32_t DiscoveryManager::InitPassiveSubInfo(const std::string &pkgNameTemp,
    const std::map<std::string, std::string> &discoverParam, DmSubscribeInfo &dmSubInfo)
{
    dmSubInfo.subscribeId = DM_INVALID_FLAG_ID;
    dmSubInfo.mode = DmDiscoverMode::DM_DISCOVER_MODE_PASSIVE;
    dmSubInfo.freq = DmExchangeFreq::DM_LOW;
    dmSubInfo.isSameAccount = false;
    dmSubInfo.isWakeRemote = false;
    if (strcpy_s(dmSubInfo.capability, DM_MAX_DEVICE_CAPABILITY_LEN, DM_CAPABILITY_APPROACH) != EOK) {
        LOGE("capability copy err.");
        return ERR_DM_ENABLE_DISCOVERY_LISTENER_FAILED;
    }
    UpdateInfoFreq(discoverParam, dmSubInfo);
    int32_t externalSubId = 0;
    int32_t ret = GetValidatedInt(discoverParam, PARAM_KEY_SUBSCRIBE_ID, 0, UINT16_MAX, externalSubId);
    if (ret == PARAM_INVALID) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        dmSubInfo.subscribeId = GenInnerSubId(pkgNameTemp, static_cast<uint16_t>(externalSubId));
    }
    ret = ApplyListenerCapability(discoverParam, dmSubInfo);
    if (ret != DM_OK) {
        return ret;
    }
    UpdateInfoMedium(discoverParam, dmSubInfo);
    return DM_OK;
}

int32_t DiscoveryManager::ApplyListenerCapability(const std::map<std::string, std::string> &discoverParam,
    DmSubscribeInfo &dmSubInfo)
{
    auto it = discoverParam.find(PARAM_KEY_DISC_CAPABILITY);
    if (it == discoverParam.end() || it->second.empty()) {
        LOGI("capability = %{public}s,", std::string(dmSubInfo.capability).c_str());
        return DM_OK;
    }
    // [P21] caller-provided capability must belong to the known capability set.
    if (!IsValidCapability(it->second) ||
        strcpy_s(dmSubInfo.capability, DM_MAX_DEVICE_CAPABILITY_LEN, it->second.c_str()) != EOK) {
        LOGE("capability is invalid or copy err.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    LOGI("capability = %{public}s,", std::string(dmSubInfo.capability).c_str());
    return DM_OK;
}

int32_t DiscoveryManager::DisableDiscoveryListener(const std::string &pkgName,
    const std::map<std::string, std::string> &extraParam)
{
    if (!IsValidPkgName(pkgName)) {
        LOGE("Invalid parameter, pkgName is invalid.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    CHECK_NULL_RETURN(softbusListener_, ERR_DM_POINT_NULL);
    LOGI("begin for pkgName = %{public}s.", pkgName.c_str());
    std::string pkgNameTemp = RemoveMultiUserIdentify(pkgName);
    if (pkgNameTemp.empty()) {
        return ERR_DM_FAILED;
    }
    uint16_t innerSubId = DM_INVALID_FLAG_ID;
    int32_t externalSubId = 0;
    int32_t ret = GetValidatedInt(extraParam, PARAM_KEY_SUBSCRIBE_ID, 0, UINT16_MAX, externalSubId);
    if (ret == PARAM_INVALID) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        innerSubId = GetAndRemoveInnerSubId(pkgNameTemp, static_cast<uint16_t>(externalSubId));
    }
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        if (capabilityMap_.find(pkgNameTemp) != capabilityMap_.end()) {
            capabilityMap_.erase(pkgNameTemp);
        }
    }
    softbusListener_->UnRegisterSoftbusLnnOpsCbk(pkgNameTemp);
    if (innerSubId == DM_INVALID_FLAG_ID) {
        LOGE("Invalid parameter, cannot find subscribeId in cache map.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    return softbusListener_->StopRefreshSoftbusLNN(innerSubId);
}

int32_t DiscoveryManager::StartDiscovering(const std::string &pkgName,
    const std::map<std::string, std::string> &discoverParam, const std::map<std::string, std::string> &filterOptions)
{
    if (!IsValidPkgName(pkgName)) {
        LOGE("Invalid parameter, pkgName is invalid.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    CHECK_NULL_RETURN(softbusListener_, ERR_DM_POINT_NULL);
    LOGI("begin for pkgName = %{public}s.", pkgName.c_str());
    std::string pkgNameTemp = AddMultiUserIdentify(pkgName);
    if (pkgNameTemp.empty()) {
        return ERR_DM_FAILED;
    }
    DmSubscribeInfo dmSubInfo;
    if (ConfigDiscParam(discoverParam, &dmSubInfo) != DM_OK) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (HandleDiscoveryQueue(pkgNameTemp, dmSubInfo.subscribeId, filterOptions) != DM_OK) {
        return ERR_DM_DISCOVERY_REPEATED;
    }
    dmSubInfo.subscribeId = GenInnerSubId(pkgNameTemp, dmSubInfo.subscribeId);
    softbusListener_->RegisterSoftbusLnnOpsCbk(pkgNameTemp, shared_from_this());
    StartDiscoveryTimer(pkgNameTemp);
    auto it = filterOptions.find(PARAM_KEY_FILTER_OPTIONS);
    if (it != filterOptions.end()) {
        JsonObject jsonObject(it->second);
        if (!jsonObject.IsDiscarded() && jsonObject.Contains(TYPE_MINE)) {
            return StartDiscovering4MineLibary(pkgNameTemp, dmSubInfo, it->second);
        }
    }
    return StartDiscoveringByMetaParam(pkgNameTemp, dmSubInfo, discoverParam);
}

int32_t DiscoveryManager::StartDiscoveringByMetaParam(const std::string &pkgName, DmSubscribeInfo &dmSubInfo,
    const std::map<std::string, std::string> &param)
{
    bool isStandardMetaNode = true;
    auto it = param.find(PARAM_KEY_META_TYPE);
    if (it != param.end()) {
        int32_t metaType = 0;
        // [P3] meta type must be numeric and within the known enum range.
        if (GetValidatedInt(param, PARAM_KEY_META_TYPE, MetaNodeType::PROXY_TRANSMISION,
            MetaNodeType::PROXY_DEFAULT, metaType) != PARAM_VALID) {
            LOGE("invalid metaType.");
            return ERR_DM_INPUT_PARA_INVALID;
        }
        isStandardMetaNode = (metaType == MetaNodeType::PROXY_TRANSMISION);
    }
    int32_t ret = isStandardMetaNode ? StartDiscoveringNoMetaType(pkgName, dmSubInfo, param) :
        StartDiscovering4MetaType(pkgName, dmSubInfo, param);
    if (ret != DM_OK) {
        LOGE("meta node process failed, ret = %{public}d", ret);
    }
    return ret;
}

int32_t DiscoveryManager::ConfigDiscParam(const std::map<std::string, std::string> &discoverParam,
    DmSubscribeInfo *dmSubInfo)
{
    if (dmSubInfo == nullptr) {
        LOGE("dmSubInfo is nullptr.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    dmSubInfo->subscribeId = DM_INVALID_FLAG_ID;
    dmSubInfo->mode = DmDiscoverMode::DM_DISCOVER_MODE_ACTIVE;
    dmSubInfo->medium = DmExchangeMedium::DM_AUTO;
    dmSubInfo->freq = DmExchangeFreq::DM_LOW;
    dmSubInfo->isSameAccount = false;
    dmSubInfo->isWakeRemote = false;
    // [P3] all numeric inputs are numeric-string and range validated before the enum/uint16 cast.
    int32_t value = 0;
    int32_t ret = GetValidatedInt(discoverParam, PARAM_KEY_SUBSCRIBE_ID, 0, UINT16_MAX, value);
    if (ret == PARAM_INVALID) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        dmSubInfo->subscribeId = static_cast<uint16_t>(value);
    }
    ret = GetValidatedInt(discoverParam, PARAM_KEY_DISC_MEDIUM, DmExchangeMedium::DM_AUTO,
        DmExchangeMedium::DM_USB, value);
    if (ret == PARAM_INVALID) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        dmSubInfo->medium = static_cast<DmExchangeMedium>(value);
    }
    ret = GetValidatedInt(discoverParam, PARAM_KEY_DISC_FREQ, DmExchangeFreq::DM_LOW,
        DmExchangeFreq::DM_EXTREME_HIGH, value);
    if (ret == PARAM_INVALID) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        dmSubInfo->freq = static_cast<DmExchangeFreq>(value);
    }
    ret = GetValidatedInt(discoverParam, PARAM_KEY_DISC_MODE, DM_DISCOVER_MODE_PASSIVE,
        DM_DISCOVER_MODE_ACTIVE, value);
    if (ret == PARAM_INVALID ||
        (ret == PARAM_VALID && value != DM_DISCOVER_MODE_PASSIVE && value != DM_DISCOVER_MODE_ACTIVE)) {
        // [P3] discover mode only has two legal values.
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (ret == PARAM_VALID) {
        dmSubInfo->mode = static_cast<DmDiscoverMode>(value);
    }
    return DM_OK;
}

int32_t DiscoveryManager::StartDiscovering4MineLibary(const std::string &pkgName, DmSubscribeInfo &dmSubInfo,
    const std::string &searchJson)
{
    // [P12] mineSoftbusListener_ is never constructed in this class; the null check prevents a crash.
    CHECK_NULL_RETURN(mineSoftbusListener_, ERR_DM_FAILED);
    // [P21] search json from the caller is length-bounded.
    if (searchJson.size() > MAX_FILTER_DATA_LEN) {
        LOGE("search json over length.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    if (strcpy_s(dmSubInfo.capability, DM_MAX_DEVICE_CAPABILITY_LEN, DM_CAPABILITY_OSD) != EOK) {
        LOGE("capability copy err.");
        return ERR_DM_START_DISCOVERING_FAILED;
    }
    LOGI("mine meta node process, pkgName = %{public}s, capability = %{public}s",
        pkgName.c_str(), std::string(dmSubInfo.capability).c_str());
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        CHECK_SIZE_RETURN(capabilityMap_, ERR_DM_START_DISCOVERING_FAILED);
        capabilityMap_[pkgName] = std::string(dmSubInfo.capability);
    }
    int32_t ret = mineSoftbusListener_->RefreshSoftbusLNN(pkgName, searchJson, dmSubInfo);
    if (ret != DM_OK) {
        LOGE("StartDiscovering for meta node process failed, ret = %{public}d", ret);
    }
    return ret;
}

int32_t DiscoveryManager::StartDiscoveringNoMetaType(const std::string &pkgName, DmSubscribeInfo &dmSubInfo,
    const std::map<std::string, std::string> &param)
{
    std::string capability = DM_CAPABILITY_OSD;
    auto it = param.find(PARAM_KEY_DISC_CAPABILITY);
    if (it != param.end() && !it->second.empty()) {
        capability = it->second;
    }
    // [P21] capability must belong to the known capability set.
    if (!IsValidCapability(capability) ||
        strcpy_s(dmSubInfo.capability, DM_MAX_DEVICE_CAPABILITY_LEN, capability.c_str()) != EOK) {
        LOGE("capability is invalid or copy err.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    LOGI("standard meta node process, pkgName = %{public}s, capability = %{public}s",
        pkgName.c_str(), std::string(dmSubInfo.capability).c_str());
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        CHECK_SIZE_RETURN(capabilityMap_, ERR_DM_START_DISCOVERING_FAILED);
        capabilityMap_[pkgName] = std::string(dmSubInfo.capability);
    }
    std::string customData = LNN_DISC_CAPABILITY;
    auto dataIter = param.find(PARAM_KEY_CUSTOM_DATA);
    if (dataIter != param.end() && !dataIter->second.empty()) {
        // [P21] custom data broadcast in discovery is length-bounded.
        if (dataIter->second.size() > MAX_CUSTOM_DATA_LEN) {
            LOGE("custom data over length.");
            return ERR_DM_INPUT_PARA_INVALID;
        }
        customData = dataIter->second;
    }
    return RefreshSoftbusLnnChecked(dmSubInfo, customData);
}

int32_t DiscoveryManager::StartDiscovering4MetaType(const std::string &pkgName, DmSubscribeInfo &dmSubInfo,
    const std::map<std::string, std::string> &param)
{
    MetaNodeType metaType = MetaNodeType::CUSTOM_UNKNOWN;
    auto it = param.find(PARAM_KEY_META_TYPE);
    if (it != param.end()) {
        LOGI("meta node process, input metaType = %{public}s, pkgName = %{public}s",
            it->second.c_str(), pkgName.c_str());
        metaType = (MetaNodeType)(std::atoi(it->second.c_str()));
    }
    int32_t ret = SetMetaCapability(metaType, dmSubInfo);
    if (ret != DM_OK) {
        return ret;
    }
    std::string customData = "";
    auto dataIter = param.find(PARAM_KEY_CUSTOM_DATA);
    if (dataIter != param.end()) {
        // [P21] custom data broadcast in discovery is length-bounded.
        if (dataIter->second.size() > MAX_CUSTOM_DATA_LEN) {
            LOGE("custom data over length.");
            return ERR_DM_INPUT_PARA_INVALID;
        }
        customData = dataIter->second;
    }
    LOGI("capability = %{public}s,", std::string(dmSubInfo.capability).c_str());
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        CHECK_SIZE_RETURN(capabilityMap_, ERR_DM_START_DISCOVERING_FAILED);
        capabilityMap_[pkgName] = std::string(dmSubInfo.capability);
    }
    return RefreshSoftbusLnnChecked(dmSubInfo, customData);
}

int32_t DiscoveryManager::SetMetaCapability(MetaNodeType metaType, DmSubscribeInfo &dmSubInfo)
{
    const char *capability = nullptr;
    switch (metaType) {
        case MetaNodeType::PROXY_SHARE:
            capability = DM_CAPABILITY_SHARE;
            break;
        case MetaNodeType::PROXY_WEAR:
            capability = DM_CAPABILITY_WEAR;
            break;
        case MetaNodeType::PROXY_CASTPLUS:
            capability = DM_CAPABILITY_CASTPLUS;
            break;
        default:
            return ERR_DM_UNSUPPORTED_METHOD;
    }
    if (strcpy_s(dmSubInfo.capability, DM_MAX_DEVICE_CAPABILITY_LEN, capability) != EOK) {
        LOGE("capability copy error.");
        return ERR_DM_FAILED;
    }
    return DM_OK;
}

int32_t DiscoveryManager::RefreshSoftbusLnnChecked(DmSubscribeInfo &dmSubInfo, const std::string &customData)
{
    CHECK_NULL_RETURN(softbusListener_, ERR_DM_POINT_NULL);
    int32_t ret = softbusListener_->RefreshSoftbusLNN(DM_PKG_NAME, dmSubInfo, customData);
    if (ret != DM_OK) {
        LOGE("softbus refresh lnn ret: %{public}d.", ret);
    }
    return ret;
}

int32_t DiscoveryManager::StopDiscovering(const std::string &pkgName, uint16_t subscribeId)
{
    if (!IsValidPkgName(pkgName)) {
        LOGE("Invalid parameter, pkgName is invalid.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    LOGI("begin for pkgName = %{public}s.", pkgName.c_str());
    std::string pkgNameTemp = RemoveMultiUserIdentify(pkgName);
    if (pkgNameTemp.empty()) {
        return ERR_DM_FAILED;
    }
    return StopDiscoveringByInnerSubId(pkgNameTemp, subscribeId);
}

void DiscoveryManager::CleanDiscoveryState(const std::string &pkgName)
{
    {
        std::lock_guard<std::mutex> autoLock(locks_);
        if (pkgNameSet_.find(pkgName) != pkgNameSet_.end()) {
            pkgNameSet_.erase(pkgName);
        }
        if (discoveryContextMap_.find(pkgName) != discoveryContextMap_.end()) {
            discoveryContextMap_.erase(pkgName);
            std::lock_guard<std::mutex> autoLock(timerLocks_);
            if (timer_ != nullptr) {
                timer_->DeleteTimer(pkgName);
            }
        }
    }
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        if (capabilityMap_.find(pkgName) != capabilityMap_.end()) {
            capabilityMap_.erase(pkgName);
        }
    }
}

int32_t DiscoveryManager::StopDiscoveringByInnerSubId(const std::string &pkgName, uint16_t subscribeId)
{
    if (pkgName.empty()) {
        LOGE("Invalid parameter, pkgName is empty.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    LOGI("begin for pkgName = %{public}s.", pkgName.c_str());
    uint16_t innerSubId = static_cast<uint16_t>(GetAndRemoveInnerSubId(pkgName, subscribeId));
    if (innerSubId == DM_INVALID_FLAG_ID) {
        LOGE("Invalid parameter, cannot find subscribeId in cache map.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    CleanDiscoveryState(pkgName);
    CHECK_NULL_RETURN(softbusListener_, ERR_DM_POINT_NULL);
    softbusListener_->UnRegisterSoftbusLnnOpsCbk(pkgName);
#if (defined(MINE_HARMONY))
    // [P12] fall back to the standard listener when the mine listener is absent.
    if (mineSoftbusListener_ != nullptr) {
        return mineSoftbusListener_->StopRefreshSoftbusLNN(innerSubId);
    }
    return softbusListener_->StopRefreshSoftbusLNN(innerSubId);
#else
    return softbusListener_->StopRefreshSoftbusLNN(innerSubId);
#endif
}

void DiscoveryManager::OnDeviceFound(const std::string &pkgName, const DmDeviceInfo &info, bool isOnline)
{
    JsonObject jsonObject(info.extraData);
    if (jsonObject.IsDiscarded()) {
        LOGE("jsonStr error");
        return;
    }
    if (!IsUint32(jsonObject, PARAM_KEY_DISC_CAPABILITY)) {
        LOGE("err json string: %{public}s", PARAM_KEY_DISC_CAPABILITY);
        return;
    }
    uint32_t capabilityType = jsonObject[PARAM_KEY_DISC_CAPABILITY].Get<uint32_t>();
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        if (capabilityMap_.find(pkgName) == capabilityMap_.end() ||
            !CompareCapability(capabilityType, capabilityMap_[pkgName])) {
            return;
        }
    }
    int32_t userId = -1;
    uint32_t tokenId = 0;
    std::string callerPkgName = "";
    GetPkgNameAndUserId(pkgName, callerPkgName, userId, tokenId);
    DeviceFilterPara filterPara;
    filterPara.isOnline = false;
    filterPara.range = info.range;
    filterPara.deviceType = info.deviceTypeId;
    std::string deviceIdHash = static_cast<std::string>(info.deviceId);
    if (isOnline && GetDeviceAclParam(callerPkgName, userId, deviceIdHash, filterPara.isOnline,
        filterPara.authForm) != DM_OK) {
        // [P13/P15] fail closed: an online device whose ACL parameters cannot be verified is not reported.
        LOGE("The found device get online param failed.");
        return;
    }
    OnDeviceFound(pkgName, capabilityType, info, filterPara);
}

bool DiscoveryManager::GetDiscoveryContext(const std::string &pkgName, DiscoveryContext &context)
{
    std::lock_guard<std::mutex> autoLock(locks_);
    auto iter = discoveryContextMap_.find(pkgName);
    if (iter == discoveryContextMap_.end()) {
        return false;
    }
    context = iter->second;
    return true;
}

void DiscoveryManager::GetFirstExternalSubId(const std::string &pkgName, uint16_t &externalSubId)
{
    std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
    // [P5] find instead of operator[] to avoid polluting the map with empty entries.
    auto pkgIter = pkgName2SubIdMap_.find(pkgName);
    if (pkgIter == pkgName2SubIdMap_.end() || pkgIter->second.empty()) {
        return;
    }
    externalSubId = pkgIter->second.begin()->first;
}

void DiscoveryManager::FindExternalSubIdByInner(const std::string &pkgName, int32_t subscribeId,
    uint16_t &externalSubId)
{
    std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
    // [P5] find instead of operator[] to avoid polluting the map with empty entries.
    auto pkgIter = pkgName2SubIdMap_.find(pkgName);
    if (pkgIter == pkgName2SubIdMap_.end()) {
        return;
    }
    for (auto iter : pkgIter->second) {
        if (iter.second == subscribeId) {
            externalSubId = iter.first;
            return;
        }
    }
}

void DiscoveryManager::OnDeviceFound(const std::string &pkgName, const uint32_t capabilityType,
    const DmDeviceInfo &info, const DeviceFilterPara &filterPara)
{
    int32_t userId = -1;
    uint32_t tokenId = 0;
    std::string callerPkgName = "";
    GetPkgNameAndUserId(pkgName, callerPkgName, userId, tokenId);
    ProcessInfo processInfo;
    processInfo.userId = userId;
    processInfo.pkgName = callerPkgName;
    processInfo.tokenId = tokenId;
    DiscoveryContext discoveryContext;
    bool isIndiscoveryContextMap = GetDiscoveryContext(pkgName, discoveryContext);
    uint16_t externalSubId = DM_INVALID_FLAG_ID;
    GetFirstExternalSubId(pkgName, externalSubId);
    DiscoveryFilter filter;
    if (!isIndiscoveryContextMap ||
        filter.IsValidDevice(discoveryContext.filterOp, discoveryContext.filters, filterPara)) {
        LOGD("pkgName = %{public}s, cabability = %{public}d", pkgName.c_str(), capabilityType);
        CHECK_NULL_VOID(listener_);
        listener_->OnDeviceFound(processInfo, externalSubId, info);
    }
}

bool DiscoveryManager::CompareCapability(uint32_t capabilityType, const std::string &capabilityStr)
{
    for (uint32_t i = 0; i < sizeof(g_capabilityMap) / sizeof(g_capabilityMap[0]); i++) {
        if (strcmp(capabilityStr.c_str(), g_capabilityMap[i].capability) == 0) {
            LOGD("capabilityType: %{public}d, capabilityStr: %{public}s", capabilityType, capabilityStr.c_str());
            return ((capabilityType >> static_cast<uint32_t>(g_capabilityMap[i].bitmap)) & 1);
        }
    }
    return false;
}

void DiscoveryManager::HandleDiscoverySuccess(const std::string &pkgName, const ProcessInfo &processInfo,
    uint16_t externalSubId)
{
    std::lock_guard<std::mutex> autoLock(locks_);
    discoveryContextMap_[pkgName].subscribeId = (uint32_t)externalSubId;
    listener_->OnDiscoverySuccess(processInfo, externalSubId);
}

void DiscoveryManager::HandleDiscoveryFailed(const std::string &pkgName, const ProcessInfo &processInfo,
    uint16_t externalSubId, int32_t result, int32_t subscribeId)
{
    CleanDiscoveryState(pkgName);
    listener_->OnDiscoveryFailed(processInfo, (uint32_t)externalSubId, result);
    CHECK_NULL_VOID(softbusListener_);
    softbusListener_->StopRefreshSoftbusLNN(subscribeId);
}

void DiscoveryManager::OnDiscoveringResult(const std::string &pkgName, int32_t subscribeId, int32_t result)
{
    LOGI("subscribeId = %{public}d, result = %{public}d.", subscribeId, result);
    if (pkgName.empty() || (listener_ == nullptr)) {
        LOGE("IDeviceManagerServiceListener is null.");
        return;
    }
    int32_t userId = -1;
    uint32_t tokenId = 0;
    std::string callerPkgName = "";
    GetPkgNameAndUserId(pkgName, callerPkgName, userId, tokenId);
    ProcessInfo processInfo;
    processInfo.userId = userId;
    processInfo.pkgName = callerPkgName;
    processInfo.tokenId = tokenId;
    uint16_t externalSubId = DM_INVALID_FLAG_ID;
    FindExternalSubIdByInner(pkgName, subscribeId, externalSubId);
    if (result == 0) {
        HandleDiscoverySuccess(pkgName, processInfo, externalSubId);
        return;
    }
    HandleDiscoveryFailed(pkgName, processInfo, externalSubId, result, subscribeId);
}

void DiscoveryManager::StartDiscoveryTimer(const std::string &pkgName)
{
    std::lock_guard<std::mutex> autoLock(timerLocks_);
    if (timer_ == nullptr) {
        timer_ = std::make_shared<DmTimer>();
    }
    // [FIX] call the member through the captured this pointer, consistent with the repo-wide pattern;
    // the original class-qualified call to a non-static member is not standard C++.
    timer_->StartTimer(pkgName, DISCOVERY_TIMEOUT,
        [this] (std::string name) {
            HandleDiscoveryTimeout(name);
        });
}

int32_t DiscoveryManager::HandleDiscoveryQueue(const std::string &pkgName, uint16_t subscribeId,
    const std::map<std::string, std::string> &filterOps)
{
    std::string filterData = "";
    auto it = filterOps.find(PARAM_KEY_FILTER_OPTIONS);
    if (it != filterOps.end()) {
        filterData = it->second;
    }
    // [P21] filter options json from the caller is length-bounded.
    if (filterData.size() > MAX_FILTER_DATA_LEN) {
        LOGE("filter options over length.");
        return ERR_DM_INPUT_PARA_INVALID;
    }
    DeviceFilterOption dmFilter;
    if ((dmFilter.TransformToFilter(filterData) != DM_OK) && (dmFilter.TransformFilterOption(filterData) != DM_OK)) {
        return ERR_DM_INPUT_PARA_INVALID;
    }
    {
        std::lock_guard<std::mutex> autoLock(locks_);
        CHECK_SIZE_RETURN(pkgNameSet_, ERR_DM_DISCOVERY_REPEATED);
        CHECK_SIZE_RETURN(discoveryContextMap_, ERR_DM_DISCOVERY_REPEATED);
        if (pkgNameSet_.find(pkgName) != pkgNameSet_.end()) {
            LOGE("repeated, pkgName : %{public}s.", pkgName.c_str());
            return ERR_DM_DISCOVERY_REPEATED;
        }
        pkgNameSet_.emplace(pkgName);
        DiscoveryContext context = {pkgName, filterData, subscribeId, dmFilter.filterOp_, dmFilter.filters_};
        discoveryContextMap_.emplace(pkgName, context);
        return DM_OK;
    }
}

void DiscoveryManager::HandleDiscoveryTimeout(const std::string &pkgName)
{
    LOGI("pkgName: %{public}s.", pkgName.c_str());
    uint16_t subscribeId = 0;
    {
        std::lock_guard<std::mutex> autoLock(locks_);
        if (pkgNameSet_.find(pkgName) == pkgNameSet_.end()) {
            LOGE("pkgName: %{public}s is not exist.", pkgName.c_str());
            return;
        }
        auto iter = discoveryContextMap_.find(pkgName);
        if (iter == discoveryContextMap_.end()) {
            LOGE("subscribeId not found by pkgName %{public}s.",
                GetAnonyString(pkgName).c_str());
            return;
        }
        subscribeId = discoveryContextMap_[pkgName].subscribeId;
    }
    StopDiscoveringByInnerSubId(pkgName, subscribeId);
    {
        std::lock_guard<std::mutex> autoLock(multiUserDiscLocks_);
        multiUserDiscMap_.erase(pkgName);
    }
}

void DiscoveryManager::UpdateInfoFreq(
    const std::map<std::string, std::string> &discoverParam, DmSubscribeInfo &dmSubInfo)
{
    if (auto it = discoverParam.find(PARAM_KEY_DISC_FREQ); it != discoverParam.end()) {
        // [P3] freq must be numeric and a legal enum value; the sentinel DM_FREQ_BUTT is rejected.
        if (!IsNumberString(it->second)) {
            LOGE("freq is not numeric.");
            return;
        }
        int32_t freq = StringToInt(it->second, DECIMALISM);
        if (freq < DmExchangeFreq::DM_LOW || freq > DmExchangeFreq::DM_EXTREME_HIGH) {
            LOGE("Invalid freq value.");
            return;
        }
        dmSubInfo.freq = static_cast<DmExchangeFreq>(freq);
    }
}

void DiscoveryManager::UpdateInfoMedium(
    const std::map<std::string, std::string> &discoverParam, DmSubscribeInfo &dmSubInfo)
{
    dmSubInfo.medium = DmExchangeMedium::DM_BLE;
    int32_t medium = 0;
    // [P3] medium must be a legal enum value.
    if (GetValidatedInt(discoverParam, PARAM_KEY_DISC_MEDIUM, DmExchangeMedium::DM_AUTO,
        DmExchangeMedium::DM_USB, medium) == PARAM_VALID) {
        dmSubInfo.medium = static_cast<DmExchangeMedium>(medium);
    }
}

int32_t DiscoveryManager::GetDeviceAclParam(const std::string &pkgName, int32_t userId, std::string deviceId,
    bool &isOnline, int32_t &authForm)
{
#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
    // [P12] zero-initialized buffer; reading uninitialized memory as the local udid is forbidden.
    char localDeviceId[DEVICE_UUID_LENGTH] = {0};
    // [P3] the GetDevUdid return value must be checked.
    if (GetDevUdid(localDeviceId, DEVICE_UUID_LENGTH) != 0) {
        LOGE("GetDevUdid failed.");
        return ERR_DM_FAILED;
    }
    std::string requestDeviceId = static_cast<std::string>(localDeviceId);
    DmDiscoveryInfo discoveryInfo;
    discoveryInfo.pkgname = pkgName;
    discoveryInfo.localDeviceId = requestDeviceId;
    discoveryInfo.remoteDeviceIdHash = deviceId;
    discoveryInfo.userId = userId;
    // [P13/P15] fail closed: when the DP dependency is unavailable, ACL parameters are unobtainable.
    if (!DiscoveryManager::IsCommonDependencyReady() || DiscoveryManager::GetCommonDependencyObj() == nullptr) {
        LOGE("common dependency is not ready.");
        SecureClearString(requestDeviceId);
        SecureClearBuffer(localDeviceId, DEVICE_UUID_LENGTH);
        return ERR_DM_FAILED;
    }
    if (DiscoveryManager::GetCommonDependencyObj()->GetDeviceAclParam(discoveryInfo, isOnline, authForm) != DM_OK) {
        LOGE("GetDeviceAclParam failed.");
        SecureClearString(requestDeviceId);
        SecureClearBuffer(localDeviceId, DEVICE_UUID_LENGTH);
        return ERR_DM_FAILED;
    }
    // [P12] clear the local udid copies after use.
    SecureClearString(requestDeviceId);
    SecureClearBuffer(localDeviceId, DEVICE_UUID_LENGTH);
#endif
    return DM_OK;
}

#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
IDeviceProfileConnector* DiscoveryManager::GetCommonDependencyObj()
{
    std::lock_guard<std::mutex> lock(comDependencyLoadLock);
    return dpConnector_;
}

bool DiscoveryManager::IsCommonDependencyReady()
{
    std::lock_guard<std::mutex> lock(comDependencyLoadLock);
    if (isSoLoaded_ && dpConnector_ != nullptr && dpConnectorHandle_ != nullptr) {
        return true;
    }
    dpConnectorHandle_ = dlopen(LIB_DM_COMDENPENDENCY_NAME, RTLD_NOW | RTLD_NODELETE | RTLD_NOLOAD);
    if (dpConnectorHandle_ == nullptr) {
        dpConnectorHandle_ = dlopen(LIB_DM_COMDENPENDENCY_NAME, RTLD_NOW | RTLD_NODELETE);
    }
    if (dpConnectorHandle_ == nullptr) {
        LOGE("load libdevicemanagerdependency so failed, errMsg: %{public}s.", dlerror());
        return false;
    }
    dlerror();
    auto func = (CreateDpConnectorFuncPtr)dlsym(dpConnectorHandle_, "CreateDpConnectorInstance");
    if (dlerror() != nullptr || func == nullptr) {
        dlclose(dpConnectorHandle_);
        LOGE("Create object function is not exist.");
        return false;
    }
    dpConnector_ = func();
    isSoLoaded_ = true;
    return true;
}

bool DiscoveryManager::CloseCommonDependencyObj()
{
    LOGI("start.");
    std::lock_guard<std::mutex> lock(comDependencyLoadLock);
    if (!isSoLoaded_ && (dpConnector_ == nullptr) && (dpConnectorHandle_ == nullptr)) {
        return true;
    }

    int32_t ret = dlclose(dpConnectorHandle_);
    if (ret != 0) {
        LOGE("close libdevicemanagerdependency failed ret = %{public}d.", ret);
        return false;
    }
    isSoLoaded_ = false;
    dpConnector_ = nullptr;
    dpConnectorHandle_ = nullptr;
    return true;
}
#endif

std::vector<uint16_t> DiscoveryManager::RemoveInnerSubIds(const std::string &pkgNameTemp,
    const std::set<uint16_t> &subscribeIdSet)
{
    std::vector<uint16_t> innerSubIds;
    std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
    auto pkgIter = pkgName2SubIdMap_.find(pkgNameTemp);
    if (pkgIter == pkgName2SubIdMap_.end()) {
        return innerSubIds;
    }
    // [P12] fix: the original code erased the whole entry in the first loop round and then
    // re-created empty entries via operator[], stopping subId 0 by mistake and leaving residues.
    for (uint16_t subId : subscribeIdSet) {
        auto subIter = pkgIter->second.find(subId);
        if (subIter != pkgIter->second.end()) {
            innerSubIds.push_back(subIter->second);
            randSubIdSet_.erase(subIter->second);
        }
    }
    pkgName2SubIdMap_.erase(pkgIter);
    return innerSubIds;
}

void DiscoveryManager::ClearDiscoveryCache(const ProcessInfo &processInfo)
{
    LOGI("PkgName: %{public}s, userId: %{public}d, tokenId: %{public}s",
        processInfo.pkgName.c_str(), processInfo.userId, GetAnonyInt32(processInfo.tokenId).c_str());
    std::string pkgName = processInfo.pkgName + "#";
    std::set<uint16_t> subscribeIdSet = ClearDiscoveryPkgName(pkgName);
    if (subscribeIdSet.empty()) {
        return;
    }
    std::string pkgNameTemp = ComposeStr(ComposeStr(processInfo.pkgName, processInfo.userId),
        processInfo.tokenId);
    CHECK_NULL_VOID(softbusListener_);
    // [P12] stop every inner subId collected from the map, then erase the whole entry once.
    std::vector<uint16_t> innerSubIds = RemoveInnerSubIds(pkgNameTemp, subscribeIdSet);
    for (uint16_t innerSubId : innerSubIds) {
        softbusListener_->StopRefreshSoftbusLNN(innerSubId);
    }
    softbusListener_->UnRegisterSoftbusLnnOpsCbk(pkgNameTemp);
    {
        std::lock_guard<std::mutex> autoLock(timerLocks_);
        CHECK_NULL_VOID(timer_);
        timer_->DeleteTimer(pkgNameTemp);
    }
}

void DiscoveryManager::CollectAndEraseDiscoveryContext(const std::string &pkgName,
    std::set<uint16_t> &subscribeIdSet)
{
    std::lock_guard<std::mutex> autoLock(locks_);
    for (auto it = pkgNameSet_.begin(); it != pkgNameSet_.end();) {
        // [P18] prefix match: a composed key that merely contains another caller's pattern must
        // not be erased, preventing cross-caller state damage.
        if (it->rfind(pkgName, 0) == 0) {
            LOGI("Erase pkgname %{public}s from pkgNameSet.", it->c_str());
            it = pkgNameSet_.erase(it);
        } else {
            ++it;
        }
    }
    for (auto it = discoveryContextMap_.begin(); it != discoveryContextMap_.end();) {
        if (it->first.rfind(pkgName, 0) == 0) {
            LOGI("Erase pkgname %{public}s from discoveryContextMap_.", it->first.c_str());
            subscribeIdSet.insert(it->second.subscribeId);
            it = discoveryContextMap_.erase(it);
        } else {
            ++it;
        }
    }
}

void DiscoveryManager::CollectSubIds(const std::map<uint16_t, uint16_t> &subIdMap,
    std::set<uint16_t> &subscribeIdSet)
{
    for (auto iter : subIdMap) {
        subscribeIdSet.insert(iter.first);
    }
}

void DiscoveryManager::EraseCapabilityAndSubIdMaps(const std::string &pkgName,
    std::set<uint16_t> &subscribeIdSet)
{
    {
        std::lock_guard<std::mutex> capLock(capabilityMapLocks_);
        for (auto it = capabilityMap_.begin(); it != capabilityMap_.end();) {
            if (it->first.rfind(pkgName, 0) == 0) {
                LOGI("Erase pkgname %{public}s from capabilityMap_.", it->first.c_str());
                it = capabilityMap_.erase(it);
            } else {
                ++it;
            }
        }
    }
    {
        std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
        for (auto it = pkgName2SubIdMap_.begin(); it != pkgName2SubIdMap_.end(); ++it) {
            if (it->first.rfind(pkgName, 0) == 0) {
                LOGI("Erase pkgname %{public}s from pkgName2SubIdMap_.", it->first.c_str());
                CollectSubIds(it->second, subscribeIdSet);
            }
        }
    }
}

std::set<uint16_t> DiscoveryManager::ClearDiscoveryPkgName(const std::string &pkgName)
{
    std::set<uint16_t> subscribeIdSet;
    CollectAndEraseDiscoveryContext(pkgName, subscribeIdSet);
    EraseCapabilityAndSubIdMaps(pkgName, subscribeIdSet);
    return subscribeIdSet;
}

std::string DiscoveryManager::AddMultiUserIdentify(const std::string &pkgName)
{
    int32_t userId = -1;
    uint32_t tokenId = 0;
#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
    MultipleUserConnector::GetCallerUserId(userId);
    MultipleUserConnector::GetCallingTokenId(tokenId);
    if (userId == -1) {
        // [P13/P18] fail closed: without caller identity the multi-user isolation key cannot be
        // composed; return empty and let the caller reject the request.
        LOGE("Get caller userId failed.");
        return "";
    }
    MultiUserDiscovery multiUserDisc;
    multiUserDisc.pkgName = pkgName;
    multiUserDisc.userId = userId;
    multiUserDisc.tokenId = tokenId;
    std::string pkgNameTemp = ComposeStr(ComposeStr(pkgName, userId), tokenId);
    {
        std::lock_guard<std::mutex> autoLock(multiUserDiscLocks_);
        CHECK_SIZE_RETURN(multiUserDiscMap_, pkgNameTemp);
        multiUserDiscMap_[pkgNameTemp] = multiUserDisc;
    }
    return pkgNameTemp;
#else
    // single-user lite builds keep the bare package name.
    return pkgName;
#endif
}

std::string DiscoveryManager::RemoveMultiUserIdentify(const std::string &pkgName)
{
    int32_t userId = -1;
    uint32_t tokenId = 0;
#if !(defined(__LITEOS_M__) || defined(LITE_DEVICE))
    MultipleUserConnector::GetCallerUserId(userId);
    MultipleUserConnector::GetCallingTokenId(tokenId);
    if (userId == -1) {
        // [P13/P18] fail closed: without caller identity the multi-user isolation key cannot be composed.
        LOGE("Get caller userId failed.");
        return "";
    }
    std::string pkgNameTemp = ComposeStr(ComposeStr(pkgName, userId), tokenId);
    {
        std::lock_guard<std::mutex> autoLock(multiUserDiscLocks_);
        if (multiUserDiscMap_.find(pkgNameTemp) != multiUserDiscMap_.end()) {
            multiUserDiscMap_.erase(pkgNameTemp);
        }
    }
    return pkgNameTemp;
#else
    // single-user lite builds keep the bare package name.
    return pkgName;
#endif
}

void DiscoveryManager::GetPkgNameAndUserId(const std::string &pkgName, std::string &callerPkgName,
    int32_t &userId, uint32_t &tokenId)
{
    {
        std::lock_guard<std::mutex> autoLock(multiUserDiscLocks_);
        if (multiUserDiscMap_.find(pkgName) != multiUserDiscMap_.end()) {
            callerPkgName = GetCallerPkgName(multiUserDiscMap_[pkgName].pkgName);
            userId = multiUserDiscMap_[pkgName].userId;
            tokenId = multiUserDiscMap_[pkgName].tokenId;
            return;
        }
    }
    LOGE("find failed PkgName %{public}s.", pkgName.c_str());
}

int32_t DiscoveryManager::GenInnerSubId(const std::string &pkgName, uint16_t subId)
{
    uint16_t tempSubId = DM_INVALID_FLAG_ID;
    {
        std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
        CHECK_SIZE_RETURN(pkgName2SubIdMap_, tempSubId);
        // [P5] find instead of operator[] to avoid polluting the map with empty entries.
        auto pkgIter = pkgName2SubIdMap_.find(pkgName);
        if (pkgIter != pkgName2SubIdMap_.end()) {
            CHECK_SIZE_RETURN(pkgIter->second, tempSubId);
            auto subIter = pkgIter->second.find(subId);
            if (subIter != pkgIter->second.end()) {
                return subIter->second;
            }
        }
        tempSubId = GenUniqueRandUint(randSubIdSet_);
        pkgName2SubIdMap_[pkgName][subId] = tempSubId;
    }
    return tempSubId;
}

int32_t DiscoveryManager::GetAndRemoveInnerSubId(const std::string &pkgName, uint16_t subId)
{
    uint16_t tempSubId = DM_INVALID_FLAG_ID;
    std::lock_guard<std::mutex> autoLock(subIdMapLocks_);
    auto pkgIter = pkgName2SubIdMap_.find(pkgName);
    if (pkgIter == pkgName2SubIdMap_.end()) {
        return tempSubId;
    }
    auto subIter = pkgIter->second.find(subId);
    if (subIter != pkgIter->second.end()) {
        tempSubId = subIter->second;
        pkgIter->second.erase(subIter);
        randSubIdSet_.erase(tempSubId);
    }
    if (pkgIter->second.empty()) {
        pkgName2SubIdMap_.erase(pkgIter);
    }
    return tempSubId;
}
} // namespace DistributedHardware
} // namespace OHOS
