export const Constant = {
  DIALOG_HEIGHT_PROPORTION: 0.8,
  HALF: 0.5,
  TOP_OFFSET_PROPORTION: 6,
  SHARE_WIDTH_PHONE: 360,
  SHARE_HEIGHT_PHONE: 355,
  SHARE_WIDTH_PAD: 519,
  SHARE_HEIGHT_PAD: 256,
};