/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Refactored artifact generated by the secure-code-refactor skill.
 * Source: services/implementation/src/authentication/auth_message_processor.cpp (unchanged).
 * Principle tags at changed sites: [P2/P3/P10] identifier validation, [P4] sensitive data
 * transport, [P5] slice/state context validation, [P12] sensitive buffer cleanup,
 * [P13] fail-safe encrypt flag default, [P21] custom field length control, [FIX] integrity bug.
 */

#include "auth_message_processor_Refactor.h"

#include <cstdint>

#include "dm_auth_manager.h"
#include "dm_anonymous.h"
#include "dm_constants.h"
#include "dm_log.h"

namespace OHOS {
namespace DistributedHardware {
const char* TAG_NET_ID = "NETID";
const char* TAG_TARGET = "TARGET";
const char* TAG_APP_OPERATION = "APPOPERATION";
const char* TAG_APP_NAME = "APPNAME";
const char* TAG_APP_DESCRIPTION = "APPDESC";
const char* TAG_GROUPIDS = "GROUPIDLIST";
const char* TAG_CUSTOM_DESCRIPTION = "CUSTOMDESC";
const char* TAG_DEVICE_TYPE = "DEVICETYPE";
const char* TAG_REQUESTER = "REQUESTER";
const char* TAG_LOCAL_DEVICE_TYPE = "LOCALDEVICETYPE";
const char* TAG_INDEX = "INDEX";
const char* TAG_SLICE_NUM = "SLICE";
const char* TAG_IS_AUTH_CODE_READY = "IS_AUTH_CODE_READY";
const char* TAG_IS_SHOW_DIALOG = "IS_SHOW_DIALOG";
const char* TAG_TOKEN = "TOKEN";
const char* TAG_CRYPTO_NAME = "CRYPTONAME";
const char* TAG_CRYPTO_VERSION = "CRYPTOVERSION";
const char* QR_CODE_KEY = "qrCode";
const char* TAG_AUTH_TOKEN = "authToken";
const char* NFC_CODE_KEY = "nfcCode";
const char* OLD_VERSION_ACCOUNT = "oldVersionAccount";

const char* TAG_PUBLICKEY = "publicKey";
const char* TAG_SESSIONKEY = "sessionKey";
const char* TAG_BIND_TYPE_SIZE = "bindTypeSize";
const char* TAG_HOST_PKGNAME = "hostPkgname";
const char* TAG_HAVECREDENTIAL = "haveCredential";
const char* TAG_CONFIRM_OPERATION = "confirmOperation";
const char* TAG_IMPORT_AUTH_CODE = "IMPORT_AUTH_CODE";
const char* TAG_CRYPTIC_MSG = "encryptMsg";
const char* TAG_SESSIONKEY_ID = "sessionKeyId";

const int32_t MSG_MAX_SIZE = 45 * 1024;
const int32_t GROUP_VISIBILITY_IS_PRIVATE = 0;
const int32_t MAX_BINDTYPE_SIZE = 1000;
constexpr int32_t MAX_DATA_LEN = 65535;
constexpr const char* TAG_VISIBILITY = "VISIBILITY";
constexpr const char* TAG_APP_THUMBNAIL = "APPTHUM";
constexpr const char* TAG_THUMBNAIL_SIZE = "THUMSIZE";

// [P2/P3/P10] length bounds for peer-supplied identifiers.
constexpr size_t MAX_DEVICE_ID_LEN = 128;
// [P21] length bound for peer-supplied custom/display fields (UI spoofing and memory abuse guard).
constexpr size_t MAX_CUSTOM_FIELD_LEN = 256;
// [P21] length bound for peer-supplied secret fields (token/authToken/importAuthCode).
constexpr size_t MAX_SECRET_FIELD_LEN = 1024;
// [P3] upper bound of locally provided app thumbnail.
constexpr size_t MAX_APP_THUMBNAIL_LEN = 10 * 1024 * 1024;
// [P3] upper bound of a single received message.
constexpr size_t MAX_RECV_MSG_SIZE = 128 * 1024;
// [P5] upper bound of slice count declared in a REQ_AUTH message sequence.
constexpr int32_t MAX_SLICE_NUM = 16;

AuthMessageProcessor::AuthMessageProcessor(std::shared_ptr<DmAuthManager> authMgr) : authMgr_(authMgr)
{
    LOGI("constructor");
    cryptoMgr_ = std::make_shared<CryptoMgr>();
}

AuthMessageProcessor::~AuthMessageProcessor()
{
    authMgr_.reset();
    if (cryptoMgr_ != nullptr) {
        // [P12] session key must be destroyed before dropping the crypto manager.
        cryptoMgr_->ClearSessionKey();
        cryptoMgr_ = nullptr;
    }
    // [P12] release context references explicitly; shared ownership keeps data alive for the manager.
    authRequestContext_.reset();
    authResponseContext_.reset();
}

void AuthMessageProcessor::SecureClearString(std::string &str)
{
    // [P12] zero the buffer before release so sensitive plaintext (authToken/keys/account info)
    // does not remain in freed heap memory.
    if (str.empty()) {
        return;
    }
    volatile char *addr = &str[0];
    for (size_t i = 0; i < str.size(); i++) {
        addr[i] = 0;
    }
    str.clear();
}

bool AuthMessageProcessor::IsEncryptEnabled()
{
    std::lock_guard<ffrt::mutex> mutexLock(encryptFlagMutex_);
    // [P13] UNSET defaults to the secure side (encrypt); only an explicit DISABLED falls back
    // to the legacy plaintext path negotiated with an old-version peer.
    return encryptFlag_ != DM_ENCRYPT_FLAG_DISABLED;
}

void AuthMessageProcessor::SetEncryptFlag(bool flag)
{
    std::lock_guard<ffrt::mutex> mutexLock(encryptFlagMutex_);
    encryptFlag_ = flag ? DM_ENCRYPT_FLAG_ENABLED : DM_ENCRYPT_FLAG_DISABLED;
}

bool AuthMessageProcessor::ParseStringField(const JsonObject &json, const char *tag, std::string &out, size_t maxLen)
{
    if (!IsString(json, tag)) {
        return false;
    }
    std::string value = json[tag].Get<std::string>();
    if (value.size() > maxLen) {
        LOGE("field %{public}s over length limit.", tag);
        return false;
    }
    out = value;
    return true;
}

bool AuthMessageProcessor::ParseInt32Field(const JsonObject &json, const char *tag, int32_t &out, int32_t minVal,
    int32_t maxVal)
{
    if (!IsInt32(json, tag)) {
        return false;
    }
    int32_t value = json[tag].Get<int32_t>();
    if (value < minVal || value > maxVal) {
        LOGE("field %{public}s out of range.", tag);
        return false;
    }
    out = value;
    return true;
}

bool AuthMessageProcessor::ParseInt64Field(const JsonObject &json, const char *tag, int64_t &out, int64_t minVal,
    int64_t maxVal)
{
    if (!IsInt64(json, tag)) {
        return false;
    }
    int64_t value = json[tag].Get<int64_t>();
    if (value < minVal || value > maxVal) {
        LOGE("field %{public}s out of range.", tag);
        return false;
    }
    out = value;
    return true;
}

bool AuthMessageProcessor::ParseBoolField(const JsonObject &json, const char *tag, bool &out)
{
    if (!IsBool(json, tag)) {
        return false;
    }
    out = json[tag].Get<bool>();
    return true;
}

//LCOV_EXCL_START
bool AuthMessageProcessor::IsPincodeImported()
{
    auto sptrAuthMgr = authMgr_.lock();
    if (sptrAuthMgr == nullptr) {
        return false;
    }
    return sptrAuthMgr->IsImportedAuthCodeValid();
}

bool AuthMessageProcessor::GetJsonObj(JsonObject &jsonObj)
{
    if (authResponseContext_ == nullptr ||
        authResponseContext_->bindType.size() > static_cast<size_t>(MAX_BINDTYPE_SIZE)) {
        LOGE("invalid bindType size.");
        // [P5] fail explicitly instead of silently emitting a malformed first message.
        return false;
    }
    if (authRequestContext_ == nullptr) {
        LOGE("authRequestContext_ is nullptr.");
        return false;
    }
    jsonObj[TAG_VER] = DM_ITF_VER;
    jsonObj[TAG_MSG_TYPE] = MSG_TYPE_REQ_AUTH;
    jsonObj[TAG_INDEX] = 0;
    jsonObj[TAG_REQUESTER] = authRequestContext_->localDeviceName;
    jsonObj[TAG_DEVICE_ID] = authRequestContext_->deviceId;
    jsonObj[TAG_LOCAL_DEVICE_ID] = authRequestContext_->localDeviceId;
    jsonObj[TAG_LOCAL_DEVICE_TYPE] = authRequestContext_->localDeviceTypeId;
    jsonObj[TAG_DEVICE_TYPE] = authRequestContext_->deviceTypeId;
    jsonObj[TAG_AUTH_TYPE] = authRequestContext_->authType;
    jsonObj[TAG_TOKEN] = authRequestContext_->token;
    jsonObj[TAG_VISIBILITY] = authRequestContext_->groupVisibility;
    if (authRequestContext_->groupVisibility == GROUP_VISIBILITY_IS_PRIVATE) {
        jsonObj[TAG_TARGET] = authRequestContext_->targetPkgName;
        jsonObj[TAG_HOST] = authRequestContext_->hostPkgName;
    }
    if (authRequestContext_->authType == AUTH_TYPE_IMPORT_AUTH_CODE) {
        jsonObj[TAG_IS_SHOW_DIALOG] = false;
    } else {
        jsonObj[TAG_IS_SHOW_DIALOG] = true;
    }
    jsonObj[TAG_APP_OPERATION] = authRequestContext_->appOperation;
    jsonObj[TAG_CUSTOM_DESCRIPTION] = authRequestContext_->customDesc;
    jsonObj[TAG_APP_NAME] = authRequestContext_->appName;
    jsonObj[TAG_APP_DESCRIPTION] = authRequestContext_->appDesc;
    jsonObj[TAG_BIND_TYPE_SIZE] = authResponseContext_->bindType.size();
    for (uint32_t item = 0; item < authResponseContext_->bindType.size(); item++) {
        std::string itemStr = std::to_string(item);
        jsonObj[itemStr] = authResponseContext_->bindType[item];
    }
    return true;
}

std::vector<std::string> AuthMessageProcessor::CreateAuthRequestMessage()
{
    LOGI("start.");
    std::vector<std::string> jsonStrVec;
    if (authRequestContext_ == nullptr) {
        LOGE("authRequestContext_ is nullptr.");
        return jsonStrVec;
    }
    size_t thumbnailTotal = authRequestContext_->appThumbnail.size();
    if (thumbnailTotal > MAX_APP_THUMBNAIL_LEN) {
        // [P3] over-sized local thumbnail is dropped instead of being sliced into a message flood.
        LOGE("appThumbnail over size, drop it.");
        thumbnailTotal = 0;
    }
    int32_t thumbnailSize = static_cast<int32_t>(thumbnailTotal);
    // [FIX] the original expression ((a / b) + (a % b) == 0 ? 0 : 1) had an operator-precedence
    // defect and produced a wrong slice count; use explicit ceiling division.
    int32_t thumbnailSlice = thumbnailSize / MSG_MAX_SIZE + ((thumbnailSize % MSG_MAX_SIZE != 0) ? 1 : 0);
    JsonObject jsonObj;
    jsonObj[TAG_SLICE_NUM] = thumbnailSlice + 1;
    jsonObj[TAG_THUMBNAIL_SIZE] = thumbnailSize;
    if (!GetJsonObj(jsonObj)) {
        return jsonStrVec;
    }
    jsonStrVec.push_back(jsonObj.Dump());
    for (int32_t idx = 0; idx < thumbnailSlice; idx++) {
        JsonObject jsonThumbnailObj;
        jsonThumbnailObj[TAG_VER] = DM_ITF_VER;
        jsonThumbnailObj[TAG_MSG_TYPE] = MSG_TYPE_REQ_AUTH;
        jsonThumbnailObj[TAG_SLICE_NUM] = thumbnailSlice + 1;
        jsonThumbnailObj[TAG_INDEX] = idx + 1;
        jsonThumbnailObj[TAG_DEVICE_ID] = authRequestContext_->deviceId;
        jsonThumbnailObj[TAG_THUMBNAIL_SIZE] = thumbnailSize;
        int32_t leftLen = thumbnailSize - idx * MSG_MAX_SIZE;
        int32_t sliceLen = (leftLen > MSG_MAX_SIZE) ? MSG_MAX_SIZE : leftLen;
        // [FIX] the original code wrote the slice payload into the first message object by mistake,
        // so slice messages were sent without thumbnail data.
        jsonThumbnailObj[TAG_APP_THUMBNAIL] = authRequestContext_->appThumbnail.substr(
            static_cast<size_t>(idx) * static_cast<size_t>(MSG_MAX_SIZE), static_cast<size_t>(sliceLen));
        jsonStrVec.push_back(jsonThumbnailObj.Dump());
    }
    return jsonStrVec;
}
//LCOV_EXCL_STOP

std::string AuthMessageProcessor::CreateSimpleMessage(int32_t msgType)
{
    LOGI("start. msgType is %{public}d", msgType);
    JsonObject jsonObj;
    jsonObj[TAG_VER] = DM_ITF_VER;
    jsonObj[TAG_MSG_TYPE] = msgType;
    switch (msgType) {
        case MSG_TYPE_NEGOTIATE:
            CreateNegotiateMessage(jsonObj);
            break;
        case MSG_TYPE_RESP_NEGOTIATE:
            CreateRespNegotiateMessage(jsonObj);
            break;
        case MSG_TYPE_SYNC_GROUP:
            CreateSyncGroupMessage(jsonObj);
            break;
        case MSG_TYPE_RESP_AUTH:
            CreateResponseAuthMessage(jsonObj);
            break;
        case MSG_TYPE_RESP_AUTH_EXT:
            CreateResponseAuthMessageExt(jsonObj);
            break;
        case MSG_TYPE_REQ_AUTH_TERMINATE:
            CreateResponseFinishMessage(jsonObj);
            break;
        case MSG_TYPE_REQ_PUBLICKEY:
        case MSG_TYPE_RESP_PUBLICKEY:
            CreatePublicKeyMessageExt(jsonObj);
            break;
        case MSG_TYPE_REQ_RECHECK_MSG:
        case MSG_TYPE_RESP_RECHECK_MSG:
            CreateReqReCheckMessage(jsonObj);
            break;
        default:
            break;
    }
    return jsonObj.Dump();
}

void AuthMessageProcessor::CreatePublicKeyMessageExt(JsonObject &json)
{
    bool encryptFlag = IsEncryptEnabled();
    CHECK_NULL_VOID(authResponseContext_);
    if (!encryptFlag) {
        LOGI("not encrypt publickey.");
        json[TAG_PUBLICKEY] = authResponseContext_->publicKey;
        return;
    }
    JsonObject jsonTemp;
    auto sptr = authMgr_.lock();
    if (sptr != nullptr && !sptr->IsSrc()) {
        authResponseContext_->localSessionKeyId = sptr->GetSessionKeyIdSync(authResponseContext_->requestId);
        jsonTemp[TAG_SESSIONKEY_ID] = authResponseContext_->localSessionKeyId;
    }
    jsonTemp[TAG_PUBLICKEY] = authResponseContext_->publicKey;
    std::string strTemp = jsonTemp.Dump();
    std::string encryptStr = "";
    CHECK_NULL_VOID(cryptoMgr_);
    if (cryptoMgr_->EncryptMessage(strTemp, encryptStr) != DM_OK) {
        // [P4] encryption failure must fail closed; never fall back to plaintext.
        LOGE("EncryptMessage failed.");
        SecureClearString(strTemp);
        return;
    }
    json[TAG_CRYPTIC_MSG] = encryptStr;
    // [P12] clear the plaintext dump that carries the session key id.
    SecureClearString(strTemp);
    return;
}

void AuthMessageProcessor::CreateResponseAuthMessageExt(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    json[TAG_REPLY] = authResponseContext_->reply;
    json[TAG_TOKEN] = authResponseContext_->token;
    json[TAG_CONFIRM_OPERATION] = authResponseContext_->confirmOperation;
    json[TAG_REQUEST_ID] = authResponseContext_->requestId;
}

void AuthMessageProcessor::CreateNegotiateMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    if (cryptoAdapter_ == nullptr) {
        json[TAG_CRYPTO_SUPPORT] = false;
    } else {
        json[TAG_CRYPTO_SUPPORT] = true;
        json[TAG_CRYPTO_NAME] = cryptoAdapter_->GetName();
        json[TAG_CRYPTO_VERSION] = cryptoAdapter_->GetVersion();
        json[TAG_DEVICE_ID] = authResponseContext_->deviceId;
    }
    json[TAG_AUTH_TYPE] = authResponseContext_->authType;
    json[TAG_REPLY] = authResponseContext_->reply;
    json[TAG_LOCAL_DEVICE_ID] = authResponseContext_->localDeviceId;
    json[TAG_ACCOUNT_GROUPID] = authResponseContext_->accountGroupIdHash;

    json[TAG_BIND_LEVEL] = authResponseContext_->bindLevel;
    json[TAG_LOCAL_ACCOUNTID] = authResponseContext_->localAccountId;
    json[TAG_LOCAL_USERID] = authResponseContext_->localUserId;
    json[TAG_ISONLINE] = authResponseContext_->isOnline;
    json[TAG_AUTHED] = authResponseContext_->authed;
    json[TAG_DMVERSION] = authResponseContext_->dmVersion;
    json[TAG_HOST] = authResponseContext_->hostPkgName;
    json[TAG_BUNDLE_NAME] = authResponseContext_->bundleName;
    json[TAG_PEER_BUNDLE_NAME] = authResponseContext_->peerBundleName;
    json[TAG_TOKENID] = authResponseContext_->tokenId;
    json[TAG_IDENTICAL_ACCOUNT] = authResponseContext_->isIdenticalAccount;
    json[TAG_HAVE_CREDENTIAL] = authResponseContext_->haveCredential;
    json[TAG_HOST_PKGLABEL] = authResponseContext_->hostPkgLabel;
    json[TAG_EDITION] = authResponseContext_->edition;
    json[TAG_REMOTE_DEVICE_NAME] = authResponseContext_->remoteDeviceName;
}

void AuthMessageProcessor::CreateRespNegotiateMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    if (cryptoAdapter_ == nullptr) {
        json[TAG_CRYPTO_SUPPORT] = false;
    } else {
        json[TAG_CRYPTO_SUPPORT] = true;
        json[TAG_CRYPTO_NAME] = cryptoAdapter_->GetName();
        json[TAG_CRYPTO_VERSION] = cryptoAdapter_->GetVersion();
        json[TAG_DEVICE_ID] = authResponseContext_->deviceId;
    }
    json[TAG_AUTH_TYPE] = authResponseContext_->authType;
    json[TAG_REPLY] = authResponseContext_->reply;
    json[TAG_LOCAL_DEVICE_ID] = authResponseContext_->localDeviceId;
    json[TAG_IS_AUTH_CODE_READY] = authResponseContext_->isAuthCodeReady;
    json[TAG_NET_ID] = authResponseContext_->networkId;

    json[TAG_LOCAL_ACCOUNTID] = authResponseContext_->localAccountId;
    json[TAG_LOCAL_USERID] = authResponseContext_->localUserId;
    json[TAG_TOKENID] = authResponseContext_->tokenId;
    json[TAG_ISONLINE] = authResponseContext_->isOnline;
    json[TAG_AUTHED] = authResponseContext_->authed;
    json[TAG_DMVERSION] = authResponseContext_->dmVersion;
    json[TAG_BIND_LEVEL] = authResponseContext_->bindLevel;
    json[TAG_IDENTICAL_ACCOUNT] = authResponseContext_->isIdenticalAccount;
    json[TAG_HAVE_CREDENTIAL] = authResponseContext_->haveCredential;
    json[TAG_BIND_TYPE_SIZE] = authResponseContext_->bindType.size();
    json[TAG_TARGET_DEVICE_NAME] = authResponseContext_->targetDeviceName;
    json[TAG_IMPORT_AUTH_CODE] = authResponseContext_->importAuthCode;
    for (uint32_t item = 0; item < authResponseContext_->bindType.size(); item++) {
        auto itemStr = std::to_string(item);
        json[itemStr] = authResponseContext_->bindType[item];
    }
}

void AuthMessageProcessor::CreateSyncGroupMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authRequestContext_);
    json[TAG_DEVICE_ID] = authRequestContext_->deviceId;
    json[TAG_GROUPIDS] = authRequestContext_->syncGroupList;
}

void AuthMessageProcessor::CreateResponseAuthMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    json[TAG_REPLY] = authResponseContext_->reply;
    json[TAG_DEVICE_ID] = authResponseContext_->deviceId;
    json[TAG_TOKEN] = authResponseContext_->token;
    if (authResponseContext_->reply != 0) {
        return;
    }
    std::string groupId = authResponseContext_->groupId;
    LOGI("groupId %{public}s", GetAnonyString(groupId).c_str());
    JsonObject jsonObject(groupId);
    if (jsonObject.IsDiscarded()) {
        LOGE("DecodeRequestAuth jsonStr error");
        return;
    }
    if (!IsString(jsonObject, TAG_GROUP_ID)) {
        LOGE("err json string.");
        return;
    }
    groupId = jsonObject[TAG_GROUP_ID].Get<std::string>();
    // [P4] groupId/groupName/authToken are group join credentials; they must be encrypted with
    // the session key before transmission instead of being sent as plaintext fields.
    JsonObject jsonSensitive;
    jsonSensitive[TAG_NET_ID] = authResponseContext_->networkId;
    jsonSensitive[TAG_REQUEST_ID] = authResponseContext_->requestId;
    jsonSensitive[TAG_GROUP_ID] = groupId;
    jsonSensitive[TAG_GROUP_NAME] = authResponseContext_->groupName;
    jsonSensitive[TAG_AUTH_TOKEN] = authResponseContext_->authToken;
    std::string plainStr = jsonSensitive.Dump();
    std::string encryptStr = "";
    if (cryptoMgr_ == nullptr || cryptoMgr_->EncryptMessage(plainStr, encryptStr) != DM_OK) {
        // [P4] fail closed: when the session key is unavailable, sensitive fields are withheld
        // rather than downgraded to plaintext.
        LOGE("EncryptMessage failed, refuse to send sensitive fields in plaintext.");
        SecureClearString(plainStr);
        return;
    }
    json[TAG_CRYPTIC_MSG] = encryptStr;
    // [P12] clear the plaintext dump that carries the auth token.
    SecureClearString(plainStr);
    LOGI("%{public}s", GetAnonyString(groupId).c_str());
}

void AuthMessageProcessor::CreateResponseFinishMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    json[TAG_REPLY] = authResponseContext_->reply;
    json[TAG_AUTH_FINISH] = authResponseContext_->isFinish;
}

int32_t AuthMessageProcessor::ParseMessage(const std::string &message)
{
    // [P3] reject over-sized messages to bound the parsing cost of malformed input.
    if (message.size() > MAX_RECV_MSG_SIZE) {
        LOGE("message over size, size %{public}zu", message.size());
        return ERR_DM_FAILED;
    }
    JsonObject jsonObject(message);
    if (jsonObject.IsDiscarded()) {
        LOGE("DecodeRequestAuth jsonStr error");
        return ERR_DM_FAILED;
    }
    if (!IsInt32(jsonObject, TAG_MSG_TYPE)) {
        LOGE("err json string, first time");
        return ERR_DM_FAILED;
    }
    int32_t msgType = jsonObject[TAG_MSG_TYPE].Get<int32_t>();
    CHECK_NULL_RETURN(authResponseContext_, ERR_DM_FAILED);
    authResponseContext_->msgType = msgType;
    LOGI("message type %{public}d", authResponseContext_->msgType);
    return DispatchParseMessage(msgType, jsonObject);
}

int32_t AuthMessageProcessor::DispatchParseMessage(int32_t msgType, JsonObject &json)
{
    switch (msgType) {
        case MSG_TYPE_NEGOTIATE:
            ParseNegotiateMessage(json);
            break;
        case MSG_TYPE_RESP_NEGOTIATE:
            ParseRespNegotiateMessage(json);
            break;
        case MSG_TYPE_REQ_AUTH:
            return ParseAuthRequestMessage(json);
        case MSG_TYPE_RESP_AUTH:
            ParseAuthResponseMessage(json);
            break;
        case MSG_TYPE_RESP_AUTH_EXT:
            ParseAuthResponseMessageExt(json);
            break;
        case MSG_TYPE_REQ_AUTH_TERMINATE:
            ParseResponseFinishMessage(json);
            break;
        case MSG_TYPE_REQ_PUBLICKEY:
        case MSG_TYPE_RESP_PUBLICKEY:
            ParsePublicKeyMessageExt(json);
            break;
        case MSG_TYPE_REQ_RECHECK_MSG:
        case MSG_TYPE_RESP_RECHECK_MSG:
            ParseReqReCheckMessage(json);
            break;
        default:
            // [P5] unknown types carry no valid state transition; keep them as no-ops but observable.
            LOGW("unknown msgType %{public}d, ignore.", msgType);
            break;
    }
    return DM_OK;
}

void AuthMessageProcessor::ParsePublicKeyMessageExt(JsonObject &json)
{
    bool encryptFlag = IsEncryptEnabled();
    if (!encryptFlag && IsString(json, TAG_PUBLICKEY)) {
        CHECK_NULL_VOID(authResponseContext_);
        authResponseContext_->publicKey = json[TAG_PUBLICKEY].Get<std::string>();
        return;
    }
    if (encryptFlag && IsString(json, TAG_CRYPTIC_MSG)) {
        std::string encryptStr = json[TAG_CRYPTIC_MSG].Get<std::string>();
        std::string decryptStr = "";
        CHECK_NULL_VOID(authResponseContext_);
        authResponseContext_->publicKey = "";
        CHECK_NULL_VOID(cryptoMgr_);
        if (cryptoMgr_->DecryptMessage(encryptStr, decryptStr) != DM_OK) {
            LOGE("DecryptMessage failed.");
            SecureClearString(encryptStr);
            return;
        }
        SecureClearString(encryptStr);
        JsonObject jsonObject(decryptStr);
        if (jsonObject.IsDiscarded()) {
            LOGE("DecodeRequestAuth jsonStr error");
            SecureClearString(decryptStr);
            return;
        }
        if (ParseStringField(jsonObject, TAG_PUBLICKEY, authResponseContext_->publicKey,
            MAX_SECRET_FIELD_LEN)) {
            LOGI("get publicKey");
        }
        if (ParseInt32Field(jsonObject, TAG_SESSIONKEY_ID, authResponseContext_->remoteSessionKeyId, 0,
            INT32_MAX)) {
            LOGI("get remoteSessionKeyId");
        }
        // [P12] clear the decrypted buffer that carries key material.
        SecureClearString(decryptStr);
        return;
    }
}

void AuthMessageProcessor::ParseAuthResponseMessageExt(JsonObject &json)
{
    LOGI("start ParseAuthResponseMessageExt");
    CHECK_NULL_VOID(authResponseContext_);
    if (IsInt32(json, TAG_REPLY)) {
        authResponseContext_->reply = json[TAG_REPLY].Get<int32_t>();
    }
    ParseStringField(json, TAG_TOKEN, authResponseContext_->token, MAX_SECRET_FIELD_LEN);
    if (IsInt32(json, TAG_CONFIRM_OPERATION)) {
        authResponseContext_->confirmOperation = json[TAG_CONFIRM_OPERATION].Get<int32_t>();
    }
    // [P10] request id must stay within the system-valid range to keep the binding request
    // strictly associated.
    ParseInt64Field(json, TAG_REQUEST_ID, authResponseContext_->requestId, MIN_REQUEST_ID, MAX_REQUEST_ID);
}

void AuthMessageProcessor::ParseResponseFinishMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    if (IsInt32(json, TAG_REPLY)) {
        authResponseContext_->reply = json[TAG_REPLY].Get<int32_t>();
    }
    if (IsBool(json, TAG_AUTH_FINISH)) {
        authResponseContext_->isFinish = json[TAG_AUTH_FINISH].Get<bool>();
    }
}

void AuthMessageProcessor::GetAuthReqMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    authResponseContext_->localDeviceId = "";
    authResponseContext_->deviceId = "";
    // [P5/P6] auth type proposed by the peer must be within the known enum range.
    ParseInt32Field(json, TAG_AUTH_TYPE, authResponseContext_->authType, AUTH_TYPE_CRE, AUTH_TYPE_UNKNOW);
    ParseStringField(json, TAG_TOKEN, authResponseContext_->token, MAX_SECRET_FIELD_LEN);
    // [P2/P3] peer identifiers must be well-formed before entering the auth context.
    ParseStringField(json, TAG_DEVICE_ID, authResponseContext_->deviceId, MAX_DEVICE_ID_LEN);
    ParseStringField(json, TAG_TARGET, authResponseContext_->targetPkgName, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_LOCAL_DEVICE_ID, authResponseContext_->localDeviceId, MAX_DEVICE_ID_LEN);
    // [P21] display/custom fields from the peer are length-bounded to prevent UI spoofing payloads.
    ParseStringField(json, TAG_APP_OPERATION, authResponseContext_->appOperation, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_CUSTOM_DESCRIPTION, authResponseContext_->customDesc, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_REQUESTER, authResponseContext_->deviceName, MAX_CUSTOM_FIELD_LEN);
    if (!ParseInt32Field(json, TAG_LOCAL_DEVICE_TYPE, authResponseContext_->deviceTypeId, 0, INT32_MAX)) {
        authResponseContext_->deviceTypeId = DmDeviceType::DEVICE_TYPE_UNKNOWN;
    }
}

bool AuthMessageProcessor::ParseAuthRequestHeader(JsonObject &json)
{
    // [P5] a new message sequence resets the reassembly state.
    recvSliceIdxSet_.clear();
    GetAuthReqMessage(json);
    authResponseContext_->appThumbnail = "";
    // [P2/P10] the device id is the anchor of the trust relationship being negotiated; it must
    // be present and well-formed.
    if (authResponseContext_->deviceId.empty() || authResponseContext_->deviceId.size() > MAX_DEVICE_ID_LEN) {
        LOGE("invalid deviceId in auth request.");
        return false;
    }
    return true;
}

int32_t AuthMessageProcessor::ParseThumbnailSlice(JsonObject &json, int32_t idx, int32_t sliceNum)
{
    if (idx <= 0 || idx >= sliceNum || !IsString(json, TAG_APP_THUMBNAIL)) {
        return DM_OK;
    }
    std::string appSliceThumbnail = json[TAG_APP_THUMBNAIL].Get<std::string>();
    size_t accumulated = authResponseContext_->appThumbnail.size();
    // [P3] a single slice must fit the slice size and the total must fit MAX_DATA_LEN; written
    // in size_t arithmetic to avoid unsigned underflow.
    if (appSliceThumbnail.size() > static_cast<size_t>(MSG_MAX_SIZE) ||
        accumulated > static_cast<size_t>(MAX_DATA_LEN) ||
        appSliceThumbnail.size() > static_cast<size_t>(MAX_DATA_LEN) - accumulated) {
        LOGE("appSliceThumbnail size is %{public}zu invalid.", appSliceThumbnail.size());
        return ERR_DM_FAILED;
    }
    authResponseContext_->appThumbnail = authResponseContext_->appThumbnail + appSliceThumbnail;
    return ERR_DM_AUTH_MESSAGE_INCOMPLETE;
}

int32_t AuthMessageProcessor::ParseBindTypeList(const JsonObject &json)
{
    if (!IsInt32(json, TAG_BIND_TYPE_SIZE)) {
        return DM_OK;
    }
    int32_t bindTypeSize = json[TAG_BIND_TYPE_SIZE].Get<int32_t>();
    // [P3] negative or over-sized bind type list is rejected.
    if (bindTypeSize < 0 || bindTypeSize > MAX_BINDTYPE_SIZE) {
        LOGE("bindTypeSize is invalid.");
        return ERR_DM_FAILED;
    }
    authResponseContext_->bindType.clear();
    ParseBindTypeItems(json, bindTypeSize);
    return DM_OK;
}

void AuthMessageProcessor::ParseBindTypeItems(const JsonObject &json, int32_t bindTypeSize)
{
    for (int32_t item = 0; item < bindTypeSize; item++) {
        std::string itemStr = std::to_string(item);
        if (!IsInt32(json, itemStr)) {
            continue;
        }
        int32_t bindTypeValue = json[itemStr].Get<int32_t>();
        // [P6] each peer-proposed bind type is independently validated before acceptance.
        if (bindTypeValue >= 0) {
            authResponseContext_->bindType.push_back(bindTypeValue);
        }
    }
}

int32_t AuthMessageProcessor::ParseAuthRequestMessage(JsonObject &json)
{
    LOGI("start ParseAuthRequestMessage");
    if (!IsInt32(json, TAG_INDEX) || !IsInt32(json, TAG_SLICE_NUM)) {
        LOGE("err json string, first.");
        return ERR_DM_FAILED;
    }
    int32_t idx = json[TAG_INDEX].Get<int32_t>();
    int32_t sliceNum = json[TAG_SLICE_NUM].Get<int32_t>();
    CHECK_NULL_RETURN(authResponseContext_, ERR_DM_FAILED);
    // [P5] slice context must be self-consistent: non-negative index, positive and bounded count,
    // index strictly below count.
    if (idx < 0 || sliceNum <= 0 || sliceNum > MAX_SLICE_NUM || idx >= sliceNum) {
        LOGE("invalid slice idx %{public}d or sliceNum %{public}d", idx, sliceNum);
        return ERR_DM_FAILED;
    }
    if (idx == 0 && !ParseAuthRequestHeader(json)) {
        return ERR_DM_FAILED;
    }
    // [P5] reject duplicated slices to prevent reassembly replay/disorder.
    if (recvSliceIdxSet_.find(idx) != recvSliceIdxSet_.end()) {
        LOGE("duplicate slice idx %{public}d", idx);
        return ERR_DM_FAILED;
    }
    recvSliceIdxSet_.insert(idx);
    int32_t thumbnailRet = ParseThumbnailSlice(json, idx, sliceNum);
    if (thumbnailRet != DM_OK) {
        return thumbnailRet;
    }
    if (IsBool(json, TAG_IS_SHOW_DIALOG)) {
        authResponseContext_->isShowDialog = json[TAG_IS_SHOW_DIALOG].Get<bool>();
    } else {
        authResponseContext_->isShowDialog = true;
    }
    return ParseBindTypeList(json);
}

void AuthMessageProcessor::ParseAuthResponseMessage(JsonObject &json)
{
    LOGI("start ParseAuthResponseMessage");
    if (!IsInt32(json, TAG_REPLY)) {
        LOGE("err json string, first time.");
        return;
    }
    CHECK_NULL_VOID(authResponseContext_);
    authResponseContext_->reply = json[TAG_REPLY].Get<int32_t>();
    ParseStringField(json, TAG_DEVICE_ID, authResponseContext_->deviceId, MAX_DEVICE_ID_LEN);
    ParseStringField(json, TAG_TOKEN, authResponseContext_->token, MAX_SECRET_FIELD_LEN);
    if (authResponseContext_->reply != 0) {
        return;
    }
    if (IsString(json, TAG_CRYPTIC_MSG)) {
        // [P4] encrypted path used by refactored peers.
        ParseEncryptedAuthResponse(json);
        return;
    }
    // Legacy plaintext path kept for old-version peers, with field validation.
    ParsePlainAuthResponse(json);
}

void AuthMessageProcessor::ParsePlainAuthResponse(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    if (!IsInt64(json, TAG_REQUEST_ID) || !IsString(json, TAG_GROUP_ID) ||
        !IsString(json, TAG_GROUP_NAME) || !IsString(json, TAG_AUTH_TOKEN)) {
        LOGE("err json string, second time.");
        return;
    }
    int64_t requestId = json[TAG_REQUEST_ID].Get<int64_t>();
    // [P10] request id must stay within the system-valid range.
    if (requestId < MIN_REQUEST_ID || requestId > MAX_REQUEST_ID) {
        LOGE("requestId out of range.");
        return;
    }
    std::string groupId = json[TAG_GROUP_ID].Get<std::string>();
    std::string groupName = json[TAG_GROUP_NAME].Get<std::string>();
    std::string authToken = json[TAG_AUTH_TOKEN].Get<std::string>();
    // [P21] group info from the peer is length-bounded before entering the auth context.
    if (groupId.size() > MAX_DEVICE_ID_LEN || groupName.size() > MAX_CUSTOM_FIELD_LEN ||
        authToken.size() > MAX_SECRET_FIELD_LEN) {
        LOGE("group info over length.");
        return;
    }
    authResponseContext_->requestId = requestId;
    authResponseContext_->groupId = groupId;
    authResponseContext_->groupName = groupName;
    authResponseContext_->authToken = authToken;
    ParseStringField(json, TAG_NET_ID, authResponseContext_->networkId, MAX_DEVICE_ID_LEN);
    LOGI("groupId = %{public}s, groupName = %{public}s",
        GetAnonyString(authResponseContext_->groupId).c_str(),
        GetAnonyString(authResponseContext_->groupName).c_str());
}

void AuthMessageProcessor::ParseEncryptedAuthResponse(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    std::string encryptStr = json[TAG_CRYPTIC_MSG].Get<std::string>();
    if (encryptStr.size() > MAX_RECV_MSG_SIZE) {
        // [P3] bound the cipher text size before decrypting.
        LOGE("encrypted auth response over size.");
        return;
    }
    std::string decryptStr = "";
    CHECK_NULL_VOID(cryptoMgr_);
    if (cryptoMgr_->DecryptMessage(encryptStr, decryptStr) != DM_OK) {
        LOGE("DecryptMessage failed.");
        SecureClearString(encryptStr);
        return;
    }
    SecureClearString(encryptStr);
    JsonObject jsonObject(decryptStr);
    if (jsonObject.IsDiscarded()) {
        LOGE("DecodeRequestAuth jsonStr error");
        SecureClearString(decryptStr);
        return;
    }
    ParsePlainAuthResponse(jsonObject);
    // [P12] clear the decrypted buffer that carries the auth token.
    SecureClearString(decryptStr);
}

void AuthMessageProcessor::ParsePkgNegotiateMessage(const JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    ParseStringField(json, TAG_LOCAL_ACCOUNTID, authResponseContext_->localAccountId, MAX_CUSTOM_FIELD_LEN);
    // [P18] user id must be non-negative so that peer data cannot poison local user isolation.
    ParseInt32Field(json, TAG_LOCAL_USERID, authResponseContext_->localUserId, 0, INT32_MAX);
    ParseInt32Field(json, TAG_BIND_LEVEL, authResponseContext_->bindLevel, INT32_MIN, INT32_MAX);
    ParseBoolField(json, TAG_ISONLINE, authResponseContext_->isOnline);
    ParseBoolField(json, TAG_IDENTICAL_ACCOUNT, authResponseContext_->isIdenticalAccount);
    ParseBoolField(json, TAG_AUTHED, authResponseContext_->authed);
    // [P2] token id must be non-negative.
    ParseInt64Field(json, TAG_TOKENID, authResponseContext_->remoteTokenId, 0, INT64_MAX);
    if (!ParseStringField(json, TAG_DMVERSION, authResponseContext_->dmVersion, MAX_CUSTOM_FIELD_LEN)) {
        authResponseContext_->dmVersion = "3.2";
    }
    ParseBoolField(json, TAG_HAVECREDENTIAL, authResponseContext_->haveCredential);
    if (ParseBindTypeList(json) != DM_OK) {
        return;
    }
    ParseStringField(json, TAG_HOST_PKGLABEL, authResponseContext_->hostPkgLabel, MAX_CUSTOM_FIELD_LEN);
}

void AuthMessageProcessor::ParseNegotiateMessage(const JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    ParseBoolField(json, TAG_CRYPTO_SUPPORT, authResponseContext_->cryptoSupport);
    ParseStringField(json, TAG_CRYPTO_NAME, authResponseContext_->cryptoName, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_CRYPTO_VERSION, authResponseContext_->cryptoVer, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_DEVICE_ID, authResponseContext_->deviceId, MAX_DEVICE_ID_LEN);
    ParseStringField(json, TAG_LOCAL_DEVICE_ID, authResponseContext_->localDeviceId, MAX_DEVICE_ID_LEN);
    // [P5/P6] auth type proposed by the peer must be within the known enum range.
    ParseInt32Field(json, TAG_AUTH_TYPE, authResponseContext_->authType, AUTH_TYPE_CRE, AUTH_TYPE_UNKNOW);
    ParseInt32Field(json, TAG_REPLY, authResponseContext_->reply, INT32_MIN, INT32_MAX);
    if (!ParseStringField(json, TAG_ACCOUNT_GROUPID, authResponseContext_->accountGroupIdHash,
        MAX_SECRET_FIELD_LEN)) {
        authResponseContext_->accountGroupIdHash = OLD_VERSION_ACCOUNT;
    }
    ParseStringField(json, TAG_HOST, authResponseContext_->hostPkgName, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_EDITION, authResponseContext_->edition, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_BUNDLE_NAME, authResponseContext_->bundleName, MAX_CUSTOM_FIELD_LEN);
    if (!ParseStringField(json, TAG_PEER_BUNDLE_NAME, authResponseContext_->peerBundleName,
        MAX_CUSTOM_FIELD_LEN)) {
        authResponseContext_->peerBundleName = authResponseContext_->hostPkgName;
    }
    ParseStringField(json, TAG_REMOTE_DEVICE_NAME, authResponseContext_->remoteDeviceName,
        MAX_CUSTOM_FIELD_LEN);
    ParsePkgNegotiateMessage(json);
}

void AuthMessageProcessor::ParseRespNegotiateMessage(const JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    ParseBoolField(json, TAG_IDENTICAL_ACCOUNT, authResponseContext_->isIdenticalAccount);
    ParseInt32Field(json, TAG_REPLY, authResponseContext_->reply, INT32_MIN, INT32_MAX);
    ParseStringField(json, TAG_LOCAL_DEVICE_ID, authResponseContext_->localDeviceId, MAX_DEVICE_ID_LEN);
    ParseBoolField(json, TAG_IS_AUTH_CODE_READY, authResponseContext_->isAuthCodeReady);
    if (!ParseStringField(json, TAG_ACCOUNT_GROUPID, authResponseContext_->accountGroupIdHash,
        MAX_SECRET_FIELD_LEN)) {
        authResponseContext_->accountGroupIdHash = OLD_VERSION_ACCOUNT;
    }
    ParseStringField(json, TAG_NET_ID, authResponseContext_->networkId, MAX_DEVICE_ID_LEN);
    ParseStringField(json, TAG_TARGET_DEVICE_NAME, authResponseContext_->targetDeviceName,
        MAX_CUSTOM_FIELD_LEN);
    ParseStringField(json, TAG_IMPORT_AUTH_CODE, authResponseContext_->importAuthCode,
        MAX_SECRET_FIELD_LEN);
    ParsePkgNegotiateMessage(json);
}

void AuthMessageProcessor::SetRequestContext(std::shared_ptr<DmAuthRequestContext> authRequestContext)
{
    authRequestContext_ = authRequestContext;
}

void AuthMessageProcessor::SetResponseContext(std::shared_ptr<DmAuthResponseContext> authResponseContext)
{
    authResponseContext_ = authResponseContext;
}

std::shared_ptr<DmAuthResponseContext> AuthMessageProcessor::GetResponseContext()
{
    return authResponseContext_;
}

std::shared_ptr<DmAuthRequestContext> AuthMessageProcessor::GetRequestContext()
{
    return authRequestContext_;
}

std::string AuthMessageProcessor::CreateDeviceAuthMessage(int32_t msgType, const uint8_t *data, uint32_t dataLen)
{
    LOGI("start, msgType %{public}d.", msgType);
    // [P3] null or over-length auth payload is rejected before entering the message.
    if (data == nullptr || dataLen == 0 || dataLen > static_cast<uint32_t>(MAX_DATA_LEN)) {
        LOGE("invalid auth data, len %{public}u", dataLen);
        return "";
    }
    JsonObject jsonObj;
    jsonObj[TAG_MSG_TYPE] = msgType;
    std::string authDataStr = std::string(reinterpret_cast<const char *>(data), dataLen);
    jsonObj[TAG_DATA] = authDataStr;
    jsonObj[TAG_DATA_LEN] = dataLen;
    return jsonObj.Dump();
}

void AuthMessageProcessor::CreateReqReCheckMessage(JsonObject &jsonObj)
{
    CHECK_NULL_VOID(authResponseContext_);
    JsonObject jsonTemp;
    jsonTemp[TAG_EDITION] = authResponseContext_->edition;
    jsonTemp[TAG_LOCAL_DEVICE_ID] = authResponseContext_->localDeviceId;
    jsonTemp[TAG_LOCAL_USERID] = authResponseContext_->localUserId;
    jsonTemp[TAG_BUNDLE_NAME] = authResponseContext_->bundleName;
    jsonTemp[TAG_BIND_LEVEL] = authResponseContext_->bindLevel;
    jsonTemp[TAG_LOCAL_ACCOUNTID] = authResponseContext_->localAccountId;
    jsonTemp[TAG_TOKENID] = authResponseContext_->tokenId;
    std::string strTemp = jsonTemp.Dump();
    std::string encryptStr = "";
    CHECK_NULL_VOID(cryptoMgr_);
    if (cryptoMgr_->EncryptMessage(strTemp, encryptStr) != DM_OK) {
        LOGE("EncryptMessage failed.");
        SecureClearString(strTemp);
        return;
    }
    jsonObj[TAG_CRYPTIC_MSG] = encryptStr;
    // [P12] clear the plaintext dump that carries local account information.
    SecureClearString(strTemp);
}

void AuthMessageProcessor::ParseReqReCheckMessage(JsonObject &json)
{
    CHECK_NULL_VOID(authResponseContext_);
    std::string encryptStr = "";
    if (IsString(json, TAG_CRYPTIC_MSG)) {
        encryptStr = json[TAG_CRYPTIC_MSG].Get<std::string>();
    }
    if (encryptStr.size() > MAX_RECV_MSG_SIZE) {
        // [P3] bound the cipher text size before decrypting.
        LOGE("recheck message over size.");
        return;
    }
    std::string decryptStr = "";
    authResponseContext_->edition = "";
    authResponseContext_->localDeviceId = "";
    authResponseContext_->localUserId = 0;
    authResponseContext_->bundleName = "";
    authResponseContext_->localBindLevel = -1;
    authResponseContext_->localAccountId = "";
    authResponseContext_->tokenId = 0;
    CHECK_NULL_VOID(cryptoMgr_);
    if (cryptoMgr_->DecryptMessage(encryptStr, decryptStr) != DM_OK) {
        LOGE("DecryptMessage failed.");
        SecureClearString(encryptStr);
        return;
    }
    SecureClearString(encryptStr);
    JsonObject jsonObject(decryptStr);
    if (jsonObject.IsDiscarded()) {
        LOGE("DecodeRequestAuth jsonStr error");
        SecureClearString(decryptStr);
        return;
    }
    ParseStringField(jsonObject, TAG_EDITION, authResponseContext_->edition, MAX_CUSTOM_FIELD_LEN);
    ParseStringField(jsonObject, TAG_LOCAL_DEVICE_ID, authResponseContext_->localDeviceId, MAX_DEVICE_ID_LEN);
    ParseInt32Field(jsonObject, TAG_LOCAL_USERID, authResponseContext_->localUserId, 0, INT32_MAX);
    ParseStringField(jsonObject, TAG_BUNDLE_NAME, authResponseContext_->bundleName, MAX_CUSTOM_FIELD_LEN);
    ParseInt32Field(jsonObject, TAG_BIND_LEVEL, authResponseContext_->localBindLevel, INT32_MIN, INT32_MAX);
    ParseStringField(jsonObject, TAG_LOCAL_ACCOUNTID, authResponseContext_->localAccountId,
        MAX_CUSTOM_FIELD_LEN);
    ParseInt64Field(jsonObject, TAG_TOKENID, authResponseContext_->tokenId, 0, INT64_MAX);
    // [P12] clear the decrypted buffer that carries peer account information.
    SecureClearString(decryptStr);
}

int32_t AuthMessageProcessor::SaveSessionKey(const uint8_t *sessionKey, const uint32_t keyLen)
{
    CHECK_NULL_RETURN(cryptoMgr_, ERR_DM_POINT_NULL);
    return cryptoMgr_->SaveSessionKey(sessionKey, keyLen);
}

int32_t AuthMessageProcessor::ProcessSessionKey(const uint8_t *sessionKey, const uint32_t keyLen)
{
    CHECK_NULL_RETURN(cryptoMgr_, ERR_DM_POINT_NULL);
    return cryptoMgr_->ProcessSessionKey(sessionKey, keyLen);
}
} // namespace DistributedHardware
} // namespace OHOS
